### PR TITLE
theme(takuya): show clock icon 

### PR DESCRIPTION
**Pull request by BoseSj**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description
Updated line 81 to show the clock icon. The following change replaces the calendar icon with the clock icon beside time, as it only shows the time in the prompt. So, the clock icon looks more suitable.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by BoseSj** [comment]
# Output

### Before Change
-_pwsh_
image
 
-_zsh_
image


### After Change
-_pwsh_
image

-_zsh_
image

# Conclusion
Feel free to suggest any edit. TY 😄

**Comment by JanDeDobbeleer** [comment]
This is only allowed by the theme authors.

**Comment by BoseSj** [comment]
Okay Cool! One more thing, I want to modify `lambdageneration` in a few places. So can I add that modified theme in the repo? If yes, is there any naming constraints or something like that as it will be basically a modified lambdageneration theme?

**Comment by JanDeDobbeleer** [comment]
if you want to, we can create the PR and ask the original creator to approve

**Comment by BoseSj** [comment]
Okay. Could the same be done for this PR too?

**Comment by JanDeDobbeleer** [comment]
I don't see why not

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 thoughts on this one?

**Review by vedantmgoyal9 — APPROVED** [review]
:shipit:

**Comment by BoseSj** [comment]
Please merge this to the main @JanDeDobbeleer. TY 😄 Happy to help.

**Pull request merged**
