### PR TITLE
feat: Julian Date format segment

### PR DESCRIPTION
**Pull request by ajaffer91**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

The Julian date format is used in some industries. This is usually in the format *YYDDD* where:

- *YY*: is the year
- *DDD*: is the day of the year

Screenshot 2021-12-06 at 16 21 49

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@ajaffer91 design question, do we want to create a new segment or add the `julian` as a value to the `time_format` property in the `time` segment?

**Comment by ajaffer91** [comment]
@JanDeDobbeleer it makes perfect sense to add to the `time` segment. To be honest I wasn't quite sure how this would be achieved so went with a new segment which helped me to understand how things work a bit more. Maybe I can have another stab at doing it now through `time`. Should I mark this PR as a draft for now, then create a new one to include the changes within the time segment?

**Comment by JanDeDobbeleer** [comment]
@ajaffer91 whatever works best for you! Just let me know and we're good to go 👍🏻

**Comment by ajaffer91** [comment]
@JanDeDobbeleer after understanding how date/time formatting in Go works it seems what I wanted can easily be achieved using the time segment and configuration so I will close this PR.

For reference:
```json
          "properties": {
            "template": "\uF5F5 {{now | date \"06002\"}}"
          }
```
Screenshot 2021-12-06 at 22 54 14

OR
```json
          "properties": {
            "time_format": "06002"
          }
```
Screenshot 2021-12-06 at 22 53 49

One question I have though is that the docs say:

> The following predefined date and timestamp format constants are also available#
> ANSIC = "Mon Jan _2 15:04:05 2006"
> UnixDate = "Mon Jan _2 15:04:05 MST 2006"
> RubyDate = "Mon Jan 02 15:04:05 -0700 2006"

Can I pass in the name (eg ANSIC) to the `template` or `time_format` property instead of the layout value? If so how?

**Pull request closed without merging**
