### PR TITLE
feat: conditional segment styles

### PR DESCRIPTION
**Pull request by NoF0rte**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description
This pull request adds the ability to conditionally style segments. This comes in handy when there are certain segments that are only enabled in certain situations.

#### Example
The following is an example using three segments. The first and second are diamond type and the first only is enabled when the environment variable `VAR` is present.
image

Setting `style_condition` to `{{ if not (empty .Env.VAR) }}powerline{{end}}` will change the segments style to `powerline` when the environment variable `VAR` is present. 
image

**Note:** `powerline_symbol` was also set to customize the powerline style.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@NoF0rte I like this one, but what if we make `style` also a template? We don't need an additional property if we do that, right?

**Comment by NoF0rte** [comment]
Sure! I didn't want to change any core aspects which is why I went with adding an additional property. Let me update this PR with that change.

**Comment by JanDeDobbeleer** [comment]
@NoF0rte also make sure to change the schema for that. Not sure how to deal with autocomplete in this case but let's figure it out.

**Comment by NoF0rte** [comment]
@JanDeDobbeleer I changed the schema to allow the enum values or anything (I believe). It might not be the best way to do it, but it seems to work.

**Comment by JanDeDobbeleer** [comment]
@NoF0rte I will have a look tomorrow in the morning, thanks!

**Comment by JanDeDobbeleer** [comment]
@NoF0rte added some changes, minor refactor. If you can validate on your end as well, we're good to go.

**Comment by NoF0rte** [comment]
Seems to work just fine on my end @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @NoF0rte for code,design,doc

**Pull request merged**
