### PR TITLE
docs: Updated configuration.md small typo.

### PR DESCRIPTION
**Pull request by jp41011**
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [ ] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

Updated small typo on docs.

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@jp41011 can you rebase?

**Comment by jp41011** [comment]
> @jp41011 can you rebase?

@JanDeDobbeleer merged changes from the main branch. Couldn't do a rebase because there were other changes to the same file. Should be good to go now.

By the way do you know why the "Validate Commits / commitlint" is failing on my pull request?
I thought I used the proper "docs: ... " to start the pull request message.
Trying to understand what I should of done differently for it to pass.

**Comment by jp41011** [comment]
> > @jp41011 can you rebase?
> 
> @JanDeDobbeleer merged changes from the main branch. Couldn't do a rebase because there were other changes to the same file. Should be good to go now.
> 
> By the way do you know why the "Validate Commits / commitlint" is failing on my pull request?
> I thought I used the proper "docs: ... " to start the commit message.
> Trying to understand what I should of done differently for it to pass.

Oh I think it was the format of my individual commit messages that were not following the proper standard...I was looking at the format of the pull request message, is that right?
Sorry about that.

**Comment by JanDeDobbeleer** [comment]
@jp41011 the easiest thing to do is case of too many divisions is to reset the branch to the remote (main), then cherry pick your commit back on top of it and force push.

You had a trailing whitespace in your change, that's why the linter complains.

**Comment by JanDeDobbeleer** [comment]
Taken into #421

**Pull request closed without merging**
