### PR TITLE
feat(block): added FillerTemplate to block

### PR DESCRIPTION
**Pull request by dusktreader**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

This change introduces a new block configuration called "FillerTemplate". This allows the user to specify a template for filler so that different behavior can be configured when the block is handling an overflow.

An example configuration might be:

```yaml
- type: prompt
  alignment: right
  filler_template: "{{ if .Overflow }} {{ else }}<#3d59a1,transparent>━</>{{ end }}"
  overflow: break
```

This would draw filler text ("-") when there is no overflow and empty space when there is an overflow.

### CODE REVIEW

**Comment by dusktreader** [comment]
Example renderings:

Given config:
```yaml
- type: prompt
  alignment: right
  filler_template: "{{ if .Overflow }} {{ else }}<#3d59a1,transparent>━</>{{ end }}"
  overflow: break
```

No Overflow:
image

With Overflow:
image

**Comment by JanDeDobbeleer** [comment]
@dusktreader you could also enable `filler` to be template-able, it doesn't need an additional property. I'll refactor this a bit so you can see how that would work.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @dusktreader for code,doc

This is pure magic 🪄! @holopin-bot @dusktreader wizard

**Comment by dusktreader** [comment]
Thanks! Your refactor is definitely a better approach. I'm excited for the next release!

**Pull request merged**
