### PR TITLE
This is my theme, i want to share this

### PR DESCRIPTION
**Pull request by di4m0nds**
### Prerequisites

- [ ] I have read and understood the `CONTRIBUTING` guide
- [ ] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes/features)

#### Normal View
image

#### Git and NodeJS View
image

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
Why close it? I'm going to have a look once I'm done with a significant PR.

**Comment by di4m0nds** [comment]
ouh sorry, I modified it, and I like most the new version haha, I'll push it again with the new version

**Comment by di4m0nds** [comment]
> Why close it? I'm going to have a look once I'm done with a significant PR.

ouh sorry, I modified it, and I like most the new version haha, I'll push it again with the new version

**Comment by JanDeDobbeleer** [comment]
@di4m0nds can you migrate the theme to config version 1? You can update oh-my-posh and use `oh-my-posh --config di4am0nd.omp.json --migrate --write` and update this PR.

**Comment by di4m0nds** [comment]
> @di4m0nds can you migrate the theme to config version 1? You can update oh-my-posh and use `oh-my-posh --config di4am0nd.omp.json --migrate --write` and update this PR.

There i updated to V2

**Pull request merged**
