### PR TITLE
feat: ignore empty header line on clear

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
relates to #3388

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Status

- [x]  ZSH
- [x] Bash
- [x] PowerShell
- [x] CMD
- [x] Fish - blocked on https://github.com/fish-shell/fish-shell/issues/6610
- [x] Nushell - no builtin for the line number and can't yet handle echo-ing the ANSI sequence

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@chrisant996 challenge/question for you. I'm looking for a way to store the cursor's position (and primarily the line we're on) in an environment variable called `POSH_CURSOR_LINE`. In bash and zsh we leverage an ANSI sequence to print the location, then parse the values from that output. Is there a way to get the information from lua, or can we also read the output by printing that ANSI sequence silently, fetch and parse the content (and will the lua process have that information)?

**Comment by chrisant996** [comment]
@JanDeDobbeleer 

re: Clink on ARM -- Some users have confirmed that Clink is working on ARM in v1.4.7 and higher. Have you tried with a recent version?

re: "store the cursor's position" -- I don't quite understand what's desired or how it will be used. Can you elaborate? Why does omp need to store the cursor? What does it do with the position? Is omp trying to simulate the `ESC [ s` and `ESC [ u` codes manually? Is omp trying to write stuff above or below (or in??) the input line?

**Comment by JanDeDobbeleer** [comment]
@chrisant996 for this feature we need to know what line we're on so that we can decide whether or not to print a first line break (empty line at the top). The way to do this is by getting the cursor position from the shell (builtin for PowerShell but also retrievable using a specific ANSI sequence. And CMD is still on my list to see if this can be solved.

> Some users have confirmed that Clink is working on ARM in v1.4.7 and higher. Have you tried with a recent version?

Works! Awesome!

**Comment by chrisant996** [comment]
> @chrisant996 for this feature we need to know what line we're on so that we can decide whether or not to print a first line break (empty line at the top).

@JanDeDobbeleer When?

- Do you mean the cursor position while the user is moving the cursor around while editing in the input line?  That isn't available, and I don't think that's something to mess around with.
- Or do you mean the cursor position right before the prompt gets displayed?  In a callback function registered via [clink.onbeginedit()](https://chrisant996.github.io/clink/clink.html#clink.onbeginedit) you could use [console.getnumlines()](https://chrisant996.github.io/clink/clink.html#console.getnumlines) minus [console.gettop()](https://chrisant996.github.io/clink/clink.html#console.gettop).

Is the goal to control how much blank space shows up between the end of the previous command, and the prompt for the current input command line?  If so, then why would omp need to know the cursor position?

If that's the goal, then with Clink you can even compact multiple blank lines before printing the prompt.  E.g. [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) does fancy stuff with that; [see here](https://github.com/chrisant996/clink-flex-prompt/blob/bec2bff1133bb028da2dc08a98e992130b9e8c38/flexprompt.lua#L1697-L1717).  That's the only reason I can think of how omp might want to use the cursor position, but none of the other shells can read from the terminal display, so that can't be how omp is using the cursor position.

**Comment by JanDeDobbeleer** [comment]
@chrisant996 we only want to know if we're on the first line, so if those functions allow for that I can see how to implement that. Thanks.

**Comment by chrisant996** [comment]
@JanDeDobbeleer Oh, do you want to know if the prompt is being shown at the top of the terminal window's visible area?

Something like this, though I haven't tried it and might be off by 1 or something:

```
if console.getnumlines() == console.get top() then
```

But I don't know for sure what console.getnumlines() reports before anything has been printed yet.

**Comment by JanDeDobbeleer** [comment]
@chrisant996 yes! I'll give that a whirl. Thanks a lot!

**Pull request merged**
