### PR TITLE
refactor: use go modules

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

[Description of the change]

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by x-danger** [comment]
Set-Theme : The term 'Set-Theme' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\HP\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:3 char:1
+ Set-Theme Paradox
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-Theme:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by x-danger** [comment]
Do this Instead :
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt fish

**Comment by DepickereSven** [comment]
@x-danger Thanks for the help your solution works!

**Comment by JanDeDobbeleer** [comment]
Why are you people having this conversation in a PR from a long time ago?

**Comment by x-danger** [comment]
I just searched for the problem I was having .. and this is the first post I found "google" .. 
should I delete my posts ?

**Comment by DepickereSven** [comment]
@JanDeDobbeleer I was following the tutorial to set Powerline for Windows Terminal on the following link: https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup 

To set the theme they say you need to add the following to your `$PROFILE ` in Powershell.

```
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Paradox
```

But that doesn't work, so I started searching and found this.

**Comment by JanDeDobbeleer** [comment]
@DepickereSven I made a PR to the docs to resolve that. It was merged but but yet deployed it seems.

**Comment by blQSheep** [comment]
I've encountered the same Issue: it returns tha  "set-theme" wasn't found as a Cmdlet, function, script etc. ask to check the name or typos

**Comment by JanDeDobbeleer** [comment]
Yes, I can't override `Set-Theme` as it's used in other modules which breaks that functionality.

**Comment by masrufjaman** [comment]
> Import-Module posh-git
> Import-Module oh-my-posh
> Set-PoshPrompt fish

@x-danger  this is working. But when we restart, it again shows this https://github.com/JanDeDobbeleer/oh-my-posh/pull/70#issuecomment-785440328 issue.

**Comment by mkstamin** [comment]
**Set-Theme**  does not work. How i will solve it. Help me

**Comment by JanDeDobbeleer** [comment]
@blQSheep @mkstamin as indicated in the [docs](https://ohmyposh.dev/docs/upgrading#i-use-an-out-of-the-box-theme), use `Set-PoshPrompt` Also see [here](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/460).

**Pull request merged**
