### PR TITLE
fix(pwsh): set initial value for `$script:ExecutionTime`

### PR DESCRIPTION
**Pull request by lewis-yeung**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

### Description

@muchisx @ander-Sgr @vunhatchuong123 I cannot validate this fix because I've never been able to reproduce the bug mentioned in #2633 and #2640 on my end. 😓 Can you do a test when this goes live?

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by muchisx** [comment]
@lewis-yeung Yes, will do - Will be using PowerShell 7.2.5 which is the one im getting the error from initially.

**Comment by muchisx** [comment]
@lewis-yeung @JanDeDobbeleer 

image

I didn't know where to comment this but yeah this PR fixed it for me! Thank you !

**Comment by ander-Sgr** [comment]
It's fixed 😄  thx..!

**Comment by vunhatchuong** [comment]
It did not completely fix the bug for me. It doesn't show the `--execution-time` error anymore. 

But the terminal output is slow every time I write a command and the UI showing `pwsh` instead of `ronny` in my case

image

**Comment by muchisx** [comment]
Well, I'm a very fresh user (literally installed ohmyposh a like an hour before posting the issue) so I don't really know what is the expected execution speed, but when I press enter for a command it does have a liiiiiiiittle delay.

also previously, when the error was being printed, the execution time module worked, it showed the execution time of the command in the prompt - but still outputed the error, so maybe that execution time evaluation function is running more than one time somehow?

**Comment by lewis-yeung** [comment]
> But the terminal output is slow every time I write a command and the UI showing `pwsh` instead of `ronny` in my case

@vunhatchuong123 That's not a bug. See [my comment in another issue](https://github.com/JanDeDobbeleer/oh-my-posh/issues/2639#issuecomment-1209085547). However, if you are using a preset "bubblesline" theme without any modifications, it should not behave this way since "bubblesline" does not contain a `transient_prompt` config.

**Comment by vunhatchuong** [comment]
> > But the terminal output is slow every time I write a command and the UI showing `pwsh` instead of `ronny` in my case
> 
> @vunhatchuong123 That's not a bug. See [my comment in another issue](https://github.com/JanDeDobbeleer/oh-my-posh/issues/2639#issuecomment-1209085547). However, if you are using a preset "bubblesline" theme without any modifications, it should not behave this way since "bubblesline" does not contain a `transient_prompt` config.

Yeah I use the default one.

**Comment by lewis-yeung** [comment]
@vunhatchuong123 Now I know why the bug appeared on your end but not mine. With a previous version of 8.27.0, I tried writting two `oh-my-posh init ...` lines like what you did (also mentioned in [another comment](https://github.com/JanDeDobbeleer/oh-my-posh/issues/2640#issuecomment-1209157882)) in the PowerShell profile, and finally I can reproduce the bug! In other words, this is actually the root cause. For the first `oh-my-posh init ...` command that has no config file specified, by default, Oh My Posh uses [a "default" theme that contains a `transient_prompt` config](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/default.omp.json#L184-L188) so that the initialization script enables the transient prompt feature in the current PowerShell session. Once enabled, even though a second `oh-my-posh init ...` command uses a config without a `transient_prompt` section, the behaviors cannot be reverted.

The following I'm gonna explain may be a little more complicated, but it's the logic of how the bug is introduced:

1. The first initialization uses a "default" config **with the transient prompt feature enabled**, so it will bind a custom function to <kbd>Enter</kbd> using `Set-PSReadLineKeyHandler`:

	https://github.com/JanDeDobbeleer/oh-my-posh/blob/35efd3cf008e306ff9d58e9414d778010bd906c7/src/shell/scripts/omp.ps1#L119-L146

2. Then there comes the second initialization that uses a config **with the transient prompt feature disabled**. However, it does not bind a new function to <kbd>Enter</kbd> since the placeholder of `::TRANSIENT::` is replaced with `false` before the initialization starts, and this prevents the above code from being executed.

3. The `prompt` function defined in the first dynamic module **doesn't actually output a prompt yet**. The `Update-PoshErrorCode` function never runs so **the `$script:ExecutionTime` variable doesn't get an initial value**:

	https://github.com/JanDeDobbeleer/oh-my-posh/blob/35efd3cf008e306ff9d58e9414d778010bd906c7/src/shell/scripts/omp.ps1#L288-L289

	that means it's always **undefined**.

4. Now the key point: due to the encapsulation and isolation features of PowerShell modules, the two dynamic modules don't share the same `$script:ExecutionTime` variable. Notice that the custom function bound to <kbd>Enter</kbd> is defined in the first dynamic module, it cannot reach any functions or variables defined in the second one. Even though the second initialization has "removed" the first dynamic module, the previously defined key handler function can still reach functions and variables defined in the first module (the logic is similar to closures), so **the command below invokes the `prompt` function defined in the first module instead of the second one**:

	https://github.com/JanDeDobbeleer/oh-my-posh/blob/35efd3cf008e306ff9d58e9414d778010bd906c7/src/shell/scripts/omp.ps1#L128

	since each press on <kbd>Enter</kbd> renders a **transient** prompt, the `Update-PoshErrorCode` function will still never run in that `prompt`:

	https://github.com/JanDeDobbeleer/oh-my-posh/blob/35efd3cf008e306ff9d58e9414d778010bd906c7/src/shell/scripts/omp.ps1#L323-L325

	thus **the `$script:ExecutionTime` variable of the first module will never be populated**, and the **undefined** variable causes OMP to receive an empty value for the `--execution-time` flag:

	https://github.com/JanDeDobbeleer/oh-my-posh/blob/35efd3cf008e306ff9d58e9414d778010bd906c7/src/shell/scripts/omp.ps1#L334

	so, a bug appears and you'll see the error message. 🤦🏻‍♂️

**EDITED:**

A similar situation can occur on `$script:ErrorCode`.

**Conclusion:** Starting from v8.27.0, it cannot work properly if we do a second initialization in the same PowerShell session to change the theme. Anyway, this is at least not a common use case so it doesn't really hurt. 😅

**Comment by vunhatchuong** [comment]
Yep remove one `oh-my-posh init ...` fix it

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung to change the theme it's sufficient to adjust the `POSH_THEME` variable. But still edit the profile 😉

**Comment by lewis-yeung** [comment]
> to change the theme it's sufficient to adjust the `POSH_THEME` variable. But still edit the profile

@JanDeDobbeleer Yeah, I know this. But if we have initialized with a theme that does not contain a transient prompt config, and then change the `POSH_THEME` environment variable to use one that does, the transient prompt feature won't work due to the current logic of initialization. So, restarting PowerShell is always required. 😄

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung true, but that's not a major issue in my opinion.

**Comment by lewis-yeung** [comment]
> true, but that's not a major issue in my opinion.

@JanDeDobbeleer Agree. After all, it's not a common use case. 😄

**Pull request merged**
