### PR TITLE
feat: don't keep duration when no command is entered 

### LINKED ISSUE #544: Show n/a for execution time if no command was invoked
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

This is a feature/wish issue.

You and your crew just helped me with another "[wishlist item](https://github.com/JanDeDobbeleer/oh-my-posh/issues/532)." Thanks for your fast response there. 

This wish is based on something I did when I was using `oh-my-posh.exe` (instead of the `oh-my-posh` module) in Windows 10. It's also something I have coded in my *nix config file for OMP. 

Basically, I go from my normal state of 90% insane to 90.0035% insane when I hit enter without entering a commend, but the prompt still shows an execution time. So in my Powershell `$PROFILE`, I had this code, which puts the execution time into an environment variable. You can see that I keep track of the prior history ID and modify the variable to read `elapsed: [n/a]` if the history ID has not increased. Can the `executiontime` section in OMP be modified to give us a way to configure what is displayed if no command was actually executed?

```
$Script:lastCommand = Get-History -Count 1

if (($null -eq $Script:lastCommand.Id) -or ($Script:lastCommand.Id -eq $global:lastHistoryId)) {
    $env:__elapsed__ = 'elapsed: [n/a]'
}
else {
    $global:lastHistoryId = $Script:lastCommand.Id

    $Script:durationFormat = 'd\.hh\:mm\:ss\.fff'
    $Script:duration = ($Script:lastCommand.Duration.ToString('d\.hh\:mm\:ss\.fff'))
    
    # remove days portion if zero:
    if ($Script:duration.Substring(0, 2) -eq '0.') {
        $Script:duration = $Script:duration.Substring(2)
        
        # remove hours/minutes portions if zero. what a hack, sorry.
        foreach ($Script:element in "hours", "minutes") {
            if ($Script:duration.Substring(0, 3) -eq '00:') {
                $Script:duration = $Script:duration.Substring(3)
            } 
            else {
                continue
            }
        }
    }   
    $env:__elapsed__ = "elapsed: $Script:duration"
}
```

### Environment
- Oh my Posh version: 3.115.0
- Theme: custom
- Operating System: Windows 10 and WSL, both versions 1 and 2, running Ubuntu 18.04 and 20.04
- Shell:  Powershell 7.1.3, bash 5.0.17(1)-release (on Ubuntu 20.4), and bash 4.4.20(1)-release (on Ubuntu 18.4)
- Terminal: Windows Terminal 1.7.572.0

### Steps to Reproduce

1. Use the `executiontime` segment
2. Run a command to produce a value for execution time for your prompt.
3. Hit the ENTER key without running a command.
3. Observe that the execution time is still displayed.

**Expected behavior:** I wish, as if by magic, to be able to customize what is displayed for execution time when no new command has been executed.

**Actual behavior:** the execution time remains displayed even though there is no new command in `history`.

### PR DESCRIPTION
**Pull request by lnu**
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [ ] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### Description

fix #544 

First version for pwsh.
zsh and bash => ok
fish => nok

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@lnu fish is by design, no?

**Comment by lnu** [comment]
@JanDeDobbeleer in fish the variable `CMD_DURATION` is used to display the execution time but in the end the behaviour in omp is not aligned with the others. It's the same as with powershell before this pull:
image

**Comment by JanDeDobbeleer** [comment]
@lnu we can use [preexec](https://github.com/fish-shell/fish-shell/pull/1666) here as well

**Comment by JanDeDobbeleer** [comment]
@lnu is this ready for review? Because LGTM!

**Comment by lnu** [comment]
what the heck.... I tested everything with fish 3.1.0 and since 3.2.0 pre_exec and post_exec don't fire when enter is hit with no command: https://github.com/fish-shell/fish-shell/issues/4829
image

I'm checking how to handle this

**Comment by sql-sith** [comment]
Thanks again for the fast response! Looks great.

**Pull request merged**
