### PR TITLE
fix(theme): use small arrow like it was previously

### PR DESCRIPTION
**Pull request by schallm**
This theme used to have a large arrow followed by a small arrow.

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

Use small arrow as second character of prompt.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@schallm I'll gladly merge if you can fix the commit message to respect the guidelines.

**Comment by JanDeDobbeleer** [comment]
@schallm the subject can't start with an upper case

**Comment by schallm** [comment]
@JanDeDobbeleer How do I fix the last issue?  There are no details about the issue?

**Comment by JanDeDobbeleer** [comment]
@schallm it's OK, that's me experimenting with something.

**Pull request merged**
