### PR TITLE
feat: add node, python, dotnet to context

### PR DESCRIPTION
**Pull request by leiyu66**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

### Description

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@GavinOsborn can you review, it's your theme? Approving is also fine.

**Comment by GavinOsborn** [comment]
Would love to review. To set expectations though - I won't get to it until the weekend.

**Comment by GavinOsborn** [comment]
Thanks for suggesting enhancements to my theme 👍

I did actually think about adding runtime support to the theme when I first created it. I was concerned about a few different things:

- Signal -> Noise. I suppose it's a little subjective, but I tried to set a high bar for the value of the information the theme contained to keep it clean yet dense with high value info.
  - Most of the information in the theme provides context to help save an engineer from making costly mistakes - deleting resources in the wrong environment, pushing to the wrong branch, etc.
  - How often to engineers truly need to know the runtime version they are using where having it available justifies it appearing on every line in the terminal?
  - For those moments where you truly do need to know the full version - you're probably going to reach for `dotnet info`, `node version` anyway, right?
- If we add `node`, `dotnet` and `python` where does it stop?
  - do we end up supporting all of the languages?
  - do we then also add other platform specific tooling like package managers, Functions and Terraform all into this theme?
  - at what point does this grow to introduce significant performance penalties with all these new segment types?
- The quality of the iconography available for some platforms is quite poor.
  - dotnet in particular. Rather than being symbolic of anything I felt most folks would mistake it for a `~` - I probably would have.
  - It took me forever to find icons that I was happy with for the initial theme 😅 

I would love to know your thoughts.

**Comment by JanDeDobbeleer** [comment]
@GavinOsborn I agree, @leiyu66 I would adjust the config locally to serve your needs.

**Pull request closed without merging**
