### PR TITLE
feat(themes): add blueish theme

### PR DESCRIPTION
**Pull request by zilmarr**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### Description

Add blueish theme.

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@zilmarr can you squash both commits into 1?

**Comment by zilmarr** [comment]
@JanDeDobbeleer sure! This is my first PR, so I hope I'm doing the right thing. Please let me know, if it's correct.

**Comment by JanDeDobbeleer** [comment]
@zilmarr there's one commit but it includes changes other than the theme. Can you rebase on top of our main branch?

**Comment by zilmarr** [comment]
@JanDeDobbeleer  Sorry about that. I hope I did it right this time

**Comment by JanDeDobbeleer** [comment]
@zilmarr don't worry, there's plenty of time. I do see you're still out of sync with our main branch. Doing a `git fetch <remote>` and quick rebase should fix that.

**Comment by zilmarr** [comment]
@JanDeDobbeleer I can't figure it out how to do it :(
I'm back to 2 commits + 1 file. 
Is it ok if I close this PR and start a new one?

**Comment by JanDeDobbeleer** [comment]
Of course! No worries, I'm at the point where I might enable squash to allow people going for an easier merge 😅

**Comment by zilmarr** [comment]
@JanDeDobbeleer thanks! and sorry for the mess!

**Pull request closed without merging**
