### PR TITLE
fix(fish): different hyperlink format on linux

### LINKED ISSUE #3287: Extra \ before ~ with path function
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Using the Path segment with the path function like this `"template": "{{ if not .Writable }}<red>\ue0a2</>{{ end }} {{ path .Path .Location }} ",` adds a \ before the ~ when in the home folder.

It does not appear with a simple `"template": " {{ .Path }} ",`

### Theme

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "transparent",
          "foreground": "lightBlue",
          "properties": {
            "alpine": "\uf300",
            "arch": "\uf303",
            "centos": "\uf304",
            "debian": "\uf306",
            "elementary": "\uf309",
            "fedora": "\uf30a",
            "gentoo": "\uf30d",
            "linux": "\ue712",
            "macos": "\ue711",
            "manjaro": "\uf312",
            "mint": "\uf30f",
            "opensuse": "\uf314",
            "raspbian": "\uf315",
            "ubuntu": "\uf31c",
            "windows": "\ue70f"
          },
          "style": "plain",
          "template": "{{ if .WSL }}\ue712 on {{ end }}{{ .Icon }} ",
          "type": "os"
        },
        {
          "background": "7",
          "foreground": "red",
          "properties": {
            "root_icon": "\uf0ad"
          },
          "style": "plain",
          "template": " \uf0e7",
          "type": "root"
        },
        {
          "background": "7",
          "foreground": "black",
          "properties": {
            "display_host": false
          },
          "style": "powerline",
          "template": " {{ if .SSHSession }}\uf817 {{ end }}{{ .UserName }}@{{ .HostName }} ",
          "type": "session"
        },
        {
          "background": "lightBlue",
          "foreground": "7",
          "properties": {
            "folder_icon": "\uf115",
            "folder_separator_icon": " \ue0b1 ",
            "style": "full"
          },
          "style": "powerline",
          "powerline_symbol": "\ue0b0",
          "template": "{{ if not .Writable }}<red>\ue0a2</>{{ end }} {{ path .Path .Location }} ",
          //"template": " {{ .Path }} ",
          "type": "path"
        },
        {
          "background": "green",
          "background_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}",
            "{{ if gt .Ahead 0 }}#49416D{{ end }}",
            "{{ if gt .Behind 0 }}#7A306C{{ end }}"
          ],
          "foreground": "black",
          "foreground_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}black{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}7{{ end }}",
            "{{ if gt .Ahead 0 }}7{{ end }}"
          ],
          "properties": {
            "branch_max_length": 25,
            "fetch_status": true,
            "fetch_upstream_icon": true,
            "github_icon": "\uf7a3"
          },
          "template": " {{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} ",
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\ue0b0"
        },
        {
          "background": "lightBlue",
          "foreground": "7",
          "properties": {
            "always_enabled": true
          },
          "style": "powerline",
          "powerline_symbol": "\ue0b0",
          "template": " {{ .FormattedMs }} ",
          "type": "executiontime"
        },
        {
          "background": "lightGreen",
          "background_templates": ["{{ if gt .Code 0 }}red{{ end }}"],
          "foreground": "7",
          "properties": {
            "always_enabled": true
          },
          "style": "powerline",
          "powerline_symbol": "\ue0b0",
          "template": " {{ if gt .Code 0 }}\uf00d {{.Code}}{{ else }}\uf00c{{ end }} ",
          "type": "exit"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "background": "transparent",
          "foreground": "7",
          "style": "plain",
          "template": "in <blue><b>{{ .Name }}</b></> ",
          "type": "shell"
        },
        {
          "background": "transparent",
          "foreground": "7",
          "style": "plain",
          "template": "at <blue><b>{{ .CurrentDate | date \"15:04:05\" }}</b></>",
          "type": "time"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "transparent",
          "foreground": "7",
          "properties": {
            "always_enabled": true
          },
          "style": "plain",
          "template": "\u276f",
          "type": "exit"
        }
      ],
      "type": "prompt"
    },
    {
      "segments": [
        {
          "type": "dotnet",
          "style": "diamond",
          "leading_diamond": " \ue0b6",
          "trailing_diamond": "\ue0b4",
          "foreground": "#43CCEA",
          "background": "#29315A",
          "template": "dotnet {{ if .Unsupported }}\uf071{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "background": "#29315A",
          "foreground": "#42E66C",
          "style": "diamond",
          "leading_diamond": " \ue0b6",
          "trailing_diamond": "\ue0b4",
          "properties": {
            "display_mode": "files",
            "fetch_package_manager": false,
            "home_enabled": false
          },
          "template": " \uf898 ",
          "type": "node"
        },
        {
          "background": "#29315A",
          "foreground": "blue",
          "properties": {
            "fetch_version": false
          },
          "style": "powerline",
          "template": " \ufcd1 ",
          "type": "go"
        },
        {
          "type": "rust",
          "style": "diamond",
          "leading_diamond": " \ue0b6",
          "trailing_diamond": "\ue0b4",
          "foreground": "#99908a",
          "background": "#29315A",
          "template": " \uE7a8 "
        }
      ],
      "type": "rprompt"
    }
  ],
  "console_title_template": "{{ .Shell }} in {{ .Folder }}{{ if .Root}} [admin]{{ end }}",
  "final_space": true,
  "secondary_prompt": {
    "background": "transparent",
    "foreground": "black",
    "template": ">"
  },
  "version": 2
}
```

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

fish

### Log output

```Shell
Version: 12.34.3
```

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

resolves #3287

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@lnu we've been here before, yet I can reproduce this and this seems to fix things.

**Comment by lnu** [comment]
Looks like an edge case 😃

**Comment by JanDeDobbeleer** [comment]
@lnu I'd say it's a bug in fish shell as it shouldn't act differently cross platform.

**Comment by lnu** [comment]
@JanDeDobbeleer  I did some tests and it brings another issue(same config as the on in the original issue):

devcontainer with zsh and latest version:
image

with fish and latest version
image

with fish before the merge:
image

**Comment by JanDeDobbeleer** [comment]
@lnu so we'll need to conclude this is a fish bug and move along. Will revert. I knew there was something I was missing. Will add that context to the code as well because I'll forget once again.

**Comment by lnu** [comment]
Could it be related to this https://github.com/fish-shell/fish-shell/issues/9340 or https://github.com/fish-shell/fish-shell/issues/9073?
I tried various stuffs and yes, it's only the tilde charcater that causes the issue. If you set `mapped_locations_enabled` to false it works(you don't have any special escape).
Looks like it will be fixed with fish 3.6(and it's definitely a fish "feature")

**Comment by lnu** [comment]
finally... it looks like the original issue comes from here: `escapeLinkTextForFishShell` 
Don't remember why it has been done but that's adding the extra `\` before `~`

**Comment by JanDeDobbeleer** [comment]
@lnu I so. We had so many issues with fish interpreting the hyperlink as a prompt escape sequence we had to add that. Just like the bug you just now re-identified.

**Comment by ADIX7** [comment]
@JanDeDobbeleer you didn't had this issue on Mac with fish, did you? So, is it a Linux only thing in fish?

**Comment by JanDeDobbeleer** [comment]
@ADIX7 yes, amd if you look in the linked thread, there's even a bug in fish for this.

**Comment by lnu** [comment]
I experience the same issue on macos:
image

So it's related to fish on all platforms.

And it applies to all chars in the [escape list](https://github.com/JanDeDobbeleer/oh-my-posh/blob/e957e5f8ccc6ce3cf0ddbc8151611d202c5040fd/src/color/ansi.go#L224):
image

And as @JanDeDobbeleer said, it's related to issues with fish not parsing correctly the special characters in the hyperlink(https://github.com/JanDeDobbeleer/oh-my-posh/pull/2268)

**Comment by lnu** [comment]
@ADIX7  One alternative is to set the `home_icon`(https://ohmyposh.dev/docs/segments/path#properties) property and display a custom icon when in your home folder(which was your initial issue).

`"home_icon": "\uf015 "`
would give:
image

**Comment by ADIX7** [comment]
`escapeLinkTextForFishShell` runs only on fish with hyperlinks, doesn't it? When does this escaping  useful? Isn't it a fix for a bug that has already been fixed in fish?

@lnu I may settle with " ~" as home_icon :smile:

**Comment by JanDeDobbeleer** [comment]
> `escapeLinkTextForFishShell` runs only on fish with hyperlinks, doesn't it? When does this escaping useful? Isn't it a fix for a bug that has already been fixed in fish?

@ADIX7 I can validate that, but so far that wasn't the case.

**Comment by ADIX7** [comment]
I have been using the patched version for 3 days and it works perfectly. I deleted the `escapeLinkTextForFishShell` function.

**Comment by JanDeDobbeleer** [comment]
@ADIX7 I'll remove for myself as well and try.

**Comment by ADIX7** [comment]
Thank you!

**Pull request merged**
