### PR TITLE
docs: Fix export flag example

### PR DESCRIPTION
**Pull request by DavidDeSloovere**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

v7.41, must use `--config` as flag
`--output` is not valid

```
> oh-my-posh config export --output ~/.mytheme.omp.yml
Error: unknown flag: --output
```

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by DavidDeSloovere** [comment]
On further reading, looks like --config is to load a config and --output is not supported when calling `oh-my-posh config export --help`.
I don't know how to export the current config to a file.

image

**Comment by JanDeDobbeleer** [comment]
@DavidDeSloovere that's because you need 7.42.0 😃

**Comment by DavidDeSloovere** [comment]
Oh my God. I'm so sorry.
Had actually just upgraded with winget. Didn't know there was a newer version.

**Comment by JanDeDobbeleer** [comment]
@DavidDeSloovere the issue is also that the docs are available faster than winget. So a breaking change like this can always happen. Your other suggestion is very welcome and correct 😁

**Pull request closed without merging**
