### PR TITLE
fix: Update the Open Weather Map icons to remove blank spaces…

### PR DESCRIPTION
**Pull request by BigBear0812**
Update the Open Weather Map segment icons to remove blank spaces. Also, add night variants to some icons to better match the Open Weather Map icon list

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### <samp>🤖 Generated by Copilot at e9ba79f</samp>

Changed the weather icons in the `owm` segment to improve the visual appearance and accuracy of the weather status. Used a different font that supports more weather symbols.

### <samp>🤖 Generated by Copilot at e9ba79f</samp>

*  Update weather status icons to use Material Design Icons font for more consistency and variety ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3819/files?diff=unified&w=0#diff-f3466da260bee7c26f73ce616c897cbbd74feea39e1005bfbd08d24ce4b30660L115-R121), [link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3819/files?diff=unified&w=0#diff-f3466da260bee7c26f73ce616c897cbbd74feea39e1005bfbd08d24ce4b30660L133-R141))

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@BigBear0812 ~~are these icons Nerd Font V3 compatible?~~ Just checked, they are.

**Comment by BigBear0812** [comment]
Yes, I believe so. I looked them up on the [Nerd Fonts Cheat Sheet](https://www.nerdfonts.com/cheat-sheet)

**Comment by JanDeDobbeleer** [comment]
@BigBear0812 thanks, I think we'll be seeing a lot more issues with these new code points. But this is a good start.

**Comment by BigBear0812** [comment]
@JanDeDobbeleer ~~Great thanks! I'm not sure what I did to miss the commit lint check. Any advice on how to fix this?~~ I see where I went wrong

**Comment by JanDeDobbeleer** [comment]
@BigBear0812 don't sweat it, I'm squashing this anyways.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @BigBear0812 for code

This is pure magic 🪄! @holopin-bot @BigBear0812 wizard

**Pull request merged**
