### PR TITLE
Advanced version code for use with bash, cmd and powershell

### PR DESCRIPTION
**Pull request by nesterenkovy**
The name of the topic is defined by a separate variable `$themeName`, the path to the topics is obtained through an environment variable `$POSH_THEMES_PATH`. This also checks and informs about errors of specifying a theme file.

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### <samp>🤖 Generated by Copilot at 04e4faf</samp>

Update the `customize.mdx` documentation with more examples and tips for theme customization. Explain how to use environment variables, separate variables, and error handling on different shells.

### <samp>🤖 Generated by Copilot at 04e4faf</samp>

*  Add documentation for customizing the oh-my-posh theme on bash, cmd, and pwsh using environment variables and error handling ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3665/files?diff=unified&w=0#diff-bc801131a5c62b2aad904a0908d5b3702547be0d5fa0fc7337085e7c5dc56759R104-R121), [link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3665/files?diff=unified&w=0#diff-bc801131a5c62b2aad904a0908d5b3702547be0d5fa0fc7337085e7c5dc56759R139-R153), [link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3665/files?diff=unified&w=0#diff-bc801131a5c62b2aad904a0908d5b3702547be0d5fa0fc7337085e7c5dc56759R258-R273))
*  Add documentation for using a custom theme on pwsh with the --config option of the oh-my-posh init command ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3665/files?diff=unified&w=0#diff-bc801131a5c62b2aad904a0908d5b3702547be0d5fa0fc7337085e7c5dc56759R235-R240))

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@nesterenkovy what does this introduce that `oh-my-posh debug` doesn't offer already? If you're looking to offer information around incorrect configs, that should be added to the init scripts rather than by the user. Although, once again, `oh-my-posh debug` will show that.

**Comment by nesterenkovy** [comment]
@JanDeDobbeleer This does not apply to the application code. My addition concerns the description of the integration methods on the site. The code examples for embedding into different shell profiles are very simple, but not informative. I had a problem where an incorrectly specified theme name or path resulted in errors.
By debugging the integration in the shell, I rewrote the code for myself, which helps me understand the cause of the error in the setup. Assuming that my work could be useful to others, I decided to share it.
If you need more detailed descriptions or anything else I am willing to help.

**Comment by JanDeDobbeleer** [comment]
@nesterenkovy I understand the addition. The thing is, `oh-my-posh debug` will also show that context. So maybe adding that information is sufficient.

**Comment by nesterenkovy** [comment]
@JanDeDobbeleer Hmm, I guess you need to add a debugging and problem analysis guide then.

**Comment by JanDeDobbeleer** [comment]
@nesterenkovy closing this in favour of a troubleshooting addition to the docs.

**Pull request closed without merging**
