### PR TITLE
fix: added missing segment types to enum

### PR DESCRIPTION
**Pull request by ivan-the-terrible**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added/updated (for bug fixes / features).

### Description

When working with the JSON for a theme, we use the JSON schema validation found at <https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/schema.json>.

When attempting to add an example segment from the docs to my own custom theme, I discovered that the segment type added errored on validation with "Value is not accepted".

image

Since the docs (<https://ohmyposh.dev/docs/configuration/general#json-schema-validation>) also point to this file, it was worth updating the enum used to validate the property to eliminate false positives.

### Work Done

Updated the `themes/schema.json` file to include the missing Segment Type enum values.
The missing items include:

- argocd
- bazel
- brewfather
- buf
- deno
- elixir
- nbgv
- nightscout
- quasar
- vala

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
We also need to add their properties and information, but I can do that afterwards. This is a legit fix already.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @ivan-the-terrible for design

This is pure magic 🪄! @holopin-bot @ivan-the-terrible wizard

**Comment by ivan-the-terrible** [comment]
> We also need to add their properties and information, but I can do that afterwards. This is a legit fix already.

I don't mind doing it! This was a great way to get my feet wet. I'll see about putting another PR if you hadn't done any work yet.

**Comment by JanDeDobbeleer** [comment]
@ivan-the-terrible go right ahead, you can look at the others and add them.

**Pull request merged**
