### PR TITLE
transient prompt

### LINKED ISSUE #553: Enable Transient Prompt
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

**how to Enable Transient Prompt in powershell7 ?** 

just like p10k in zsh 

[](https://imgtu.com/i/659DsA)

### Environment

- Oh my Posh version:
- Theme:
- Operating System: win10
- Shell: powershell 7
- Terminal: windows terminal

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

Resolves #553

anim

### Tips

If you're not comfortable working with git, we're working a [guide][docs] to help you out.
Oh My Posh advises [GitKraken][kraken] as your preferred cross platfrom git GUI powertool.

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary
[docs]: https://ohmyposh.dev/docs/contributing_git
[kraken]: https://www.gitkraken.com/invite/nQmDPR9D

### CODE REVIEW

**Comment by silverqx** [comment]
It doesn't work for me, I tried both single line and multiline prompts and tried to output `echo a` few times in a row.

If I tried a single line prompt with commands like you have used in your gif, so `ls` and then `git status`, then it behaves correctly, but it doesn't with multiline prompt, the first prompt line is not removed.

And outputting `echo a` doesn't have correct output with both single and multiline prompts.

How do you record that terminal `gif`? @JanDeDobbeleer

**Comment by silverqx** [comment]
And I have not used any config options described at [Beta](https://ohmyposh.dev/docs/beta#transient-prompt), just default configuration which is provided for this `Transient prompt` feature.

**Comment by JanDeDobbeleer** [comment]
@silverqx that's why it's a beta 😁 It works perfectly on "my machine". I'm looking at this this evening. Can you share the `$PROFILE` and config you have?

**Comment by silverqx** [comment]
That is absolutely normal that something doesn't behave as you expected, classic 😎.

I have tried `agnoster` theme as a single line prompt and `slimfat` as a multi-line prompt on `PowerShell 7.1.3`.

And of course, I have tried also with my custom `cs_sorin` theme.

[Microsoft.PowerShell_profile.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6693261/Microsoft.PowerShell_profile.zip)
[cs_sorin.omp.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6693292/cs_sorin.omp.zip)

**Comment by silverqx** [comment]
Can you advise me how to record that PowerShell terminal gifs? thank you @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
@silverqx I actually screen record on my Mac, then use [gifski](https://github.com/sindresorhus/Gifski) to convert it for easy upload 😄

**Comment by silverqx** [comment]
Ok, so that is not for me, I'm on win, I will have to find another solution for these gifs, but thx for the advice.

I have also updated my comment above, added my custom `cs_sorin` theme, just to remind. 🙂

**Comment by silverqx** [comment]
Ok, I have created gif:

transient_bugs

**Comment by JanDeDobbeleer** [comment]
Alright. Pretty sure that's going to be a Windows Terminal bug. Let me check.

**Comment by JanDeDobbeleer** [comment]
@silverqx did you set the vertical offset in your theme? Because you need to as you have a multiline prompt in both btw.

**Comment by silverqx** [comment]
I'm going to check it

**Comment by silverqx** [comment]
No, this is how I have set 2 blocks:
```
{
    {
        "type": "prompt",
        "alignment": "left",
        "horizontal_offset": 0,
        "vertical_offset": 0
    },
    {
        "type": "prompt",
        "alignment": "left",
        "newline": true
    }
}
```

When I set `vertical offset: 1` for the second block, then it adds one empty line between blocks.
I have tried few combinations of `horizontal_offset`, `vertical offset`, and `newline`, but only the above-pasted configuration works for me.

**Comment by JanDeDobbeleer** [comment]
I'll make sure to help you later today 😉

**Comment by silverqx** [comment]
@JanDeDobbeleer 🙏

**Comment by JanDeDobbeleer** [comment]
@silverqx try this one, you really need to set ` "vertical_offset": -1` right now. I can however improve this by validating how many blocks have `newline: true` set.

```json
{
  "final_space": false,
  "osc99": true,
  "console_title": true,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "horizontal_offset": 0,
      "vertical_offset": 0,
      "segments": [
        {
          "type": "root",
          "style": "plain",
          "foreground": "#cece04",
          "properties": {
            "prefix": ""
          }
        },
        {
          "type": "executiontime",
          "style": "plain",
          "foreground": "#d0666f",
          "properties": {
            "threshold": 300,
            "style": "austin",
            "prefix": " "
          }
        },
        {
          "type": "path",
          "style": "plain",
          "foreground": "#0973c0",
          "properties": {
            "style": "full",
            "prefix": " "
          }
        },
        {
          "type": "git",
          "style": "plain",
          "foreground": "#c1c106",
          "properties": {
            "display_stash_count": true,
            "display_upstream_icon": true,
            "display_status": true,
            "status_colors_enabled": true,
            "color_background": false,
            "local_changes_color": "#ffeb3b",
            "working_color": "#e84855",
            "staging_color": "#2fda4e",
            "ahead_color": "#2ec4b6",
            "behind_color": "#8a4fff",
            "prefix": ""
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "type": "exit",
          "style": "plain",
          "foreground": "#cb4b16",
          "properties": {
            "always_enabled": false,
            "always_numeric": false,
            "prefix": "",
            "postfix": " "
          }
        },
        {
          "type": "exit",
          "style": "plain",
          "properties": {
            "always_enabled": true,
            "display_exit_code": false,
            "success_icon": "<#219635>λ</>",
            "error_icon": "<#cb4b16></>",
            "prefix": "",
            "postfix": " "
          }
        }
      ]
    }
  ],
  "transient_prompt": {
    "vertical_offset": -1
  }
}
```

**Comment by silverqx** [comment]
Still doesn't work as expected, I think this simple `echo a ` command is a good example of how to test this `Transient prompt` feature if it works correctly 😁

**Comment by JanDeDobbeleer** [comment]
@silverqx well that works like a charm on my machine. Given that's iTerm2 on macOS and vscode on macOS with your theme, I'd say I'll have to debug on Windows 😊

Is that Powershell 5 or 7? Could also have to do with PSReadLine not being up to date.

**Comment by silverqx** [comment]
Ohh, I thought you can reproduce it on your side, so it looks I will have to test it on manjaro later, how it looks there and I also try to disable everything else, like other PS modules which I have installed and also try to disable other customizations, I let know results latter.

I'm on Powershell 7.1.3 and PSReadLine 2.1.0.

**Comment by silverqx** [comment]
I have tried on manjaro and it works correctly with `vertical_offset: -1`, but it inserts one empty line between the prompt and output.

So I investigated further and started removing all customizations from my profile one by one and I don't know if you will be surprised what causes this problem, but here it is 👀:
```
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
```

After the above command can be reproduced on manjaro and on win too.
@JanDeDobbeleer Do you have any idea why it causes so strange behavior? Because it looks like it has nothing to do with it. 🤔

**Comment by lisonge** [comment]
There will be an `undesired behavior` with a `multi-line command`.

image



here `vertical_offset=0`

**Comment by silverqx** [comment]
Multiline commands behave buggy too @lisonge 

It looks like it is more complex than it seemed, there is too many combinations that may occur, it will need some time to catch them all. 😎 But in the end, we are in no hurry. 🤙

**Comment by JanDeDobbeleer** [comment]
@lisonge that's how we get the multiline command in from psreadline (so I don't think I can change that). The fact that you see the line on the wrong level is because `vertical_offset=0` which should be  `vertical_offset=-1`. But let me remove that variable.

**Comment by JanDeDobbeleer** [comment]
@silverqx I can't reproduce the issue where your echo a command stays on the screen:

image

**Comment by lisonge** [comment]
@JanDeDobbeleer 

this bug doesn't contact it `vertical_offset`

the problem is the `multi-line command` become `one-line command` after press `enter`

now `vertical_offset=-1` in following gif


<details>
  <summary>my schema.json</summary>
<pre><code>
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh3/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": []
    },
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "type": "os",
          "style": "diamond",
          "foreground": "#000000",
          "background": "#d3d7cf",
          "leading_diamond": "╭─"
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#e4e4e4",
          "background": "#3465a4",
          "properties": {
            "prefix": " \uF07C ",
            "home_icon": "~",
            "style": "full"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#000000",
          "background": "#4e9a06",
          "properties": {
            "branch_icon": "\uF126 ",
            "display_stash_count": true,
            "display_upstream_icon": true,
            "status_colors_enabled": true,
            "local_changes_color": "#c4a000",
            "ahead_and_behind_color": "#f26d50",
            "behind_color": "#4e9a06",
            "ahead_color": "#89d1dc",
            "stash_count_icon": "\uF692 "
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "node",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#ffffff",
          "background": "#689f63",
          "properties": {
            "postfix": " \uF898 ",
            "display_version": true
          }
        },
        {
          "type": "go",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#111111",
          "background": "#00acd7",
          "properties": {
            "postfix": " \uE627 ",
            "display_version": true
          }
        },
        {
          "type": "julia",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#111111",
          "background": "#4063D8",
          "properties": {
            "postfix": " \uE624 ",
            "display_version": true
          }
        },
        {
          "type": "python",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#111111",
          "background": "#FFDE57",
          "properties": {
            "postfix": " \uE235 ",
            "display_version": true,
            "display_mode": "files",
            "display_virtual_env": false
          }
        },
        {
          "type": "ruby",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#ffffff",
          "background": "#AE1401",
          "properties": {
            "postfix": " \uE791 ",
            "display_version": true,
            "display_mode": "files"
          }
        },
        {
          "type": "azfunc",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#ffffff",
          "background": "#FEAC19",
          "properties": {
            "postfix": " \uf0e7",
            "display_version": false,
            "display_mode": "files"
          }
        },
        {
          "type": "aws",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#ffffff",
          "background_templates": [
            "{{if contains \"default\" .Profile}}#FFA400{{end}}",
            "{{if contains \"jan\" .Profile}}#f1184c{{end}}"
          ],
          "properties": {
            "postfix": " \uE7AD ",
            "display_default": false
          }
        },
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#111111",
          "background": "#ffff66",
          "properties": {
            "root_icon": "\uF0AD"
          }
        },
        {
          "type": "executiontime",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#000000",
          "background": "#c4a000",
          "properties": {
            "postfix": " \uF252 "
          }
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": true,
          "foreground": "#d3d7cf",
          "background": "#000000",
          "properties": {
            "always_enabled": true,
            "display_exit_code": true,
            "error_color": "#cc2222",
            "color_background": true,
            "success_icon": "✔"
          }
        },
        {
          "type": "time",
          "style": "diamond",
          "invert_powerline": true,
          "trailing_diamond": "",
          "background": "#d3d7cf",
          "foreground": "#000000",
          "properties": {
            "postfix": " \uF017 "
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "type": "text",
          "style": "diamond",
          "background": "#d3d7cf",
          "trailing_diamond": "\b╰─",
          "properties": {
            "text": "\b"
          }
        }
      ]
    },
    {
      "type": "rprompt",
      "segments": [
        {
          "type": "text",
          "style": "diamond",
          "background": "#d3d7cf",
          // "trailing_diamond": "─╯",
          "properties": {
            "text": ""
          }
        }
      ]
    }
  ],
  "final_space": true,
  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{.User}} in {{ .Folder }}",
  "transient_prompt": {
    "background": "transparent",
    "foreground": "#ffffff",
    "vertical_offset": -1,
    "template": "{{ .Shell }}> <#f7dc66>{{ .Command }}</>"
  }
}

</code></pre>
</details>

**Comment by JanDeDobbeleer** [comment]
@lisonge ah OK, I see. What's odd is that this doesn't happen on my machine. It still gives me a single line prompt, but the cursor is at the correct position to write the simple prompt. I'll try to reproduce this 👍🏻

**Comment by silverqx** [comment]
You have to use a multiline prompt and use `HistorySearchBackward` to select the command. I hope this helps you to reproduce it 🤔 @JanDeDobbeleer 

Steps to reproduce:
 - open new terminal
 - `Set-PoshPrompt -Theme slimfat`
 - `echo a` ( just to save to the history )
 - `Enable-PoshTransientPrompt`
 - hit `F8` until `echo a` shows up ( HistorySearchBackward ) and hit enter
 - repeat the previous step, because the first call of `echo a` might not cause a problem, after the second and next calls of `echo a` it will stay on the screen between command and output

**Comment by silverqx** [comment]
@JanDeDobbeleer All the following is true for multiline prompts, single line prompts are ok.

Currently the output for single line command looks like this:
```
pwsh> echo a

a
pwsh> echo a

a
Here is the prompt
```

Can we make the output like?:
```
pwsh> echo a
a
pwsh> echo a
a

Here is the prompt
```

This can also solve the bug with `echo a` stays on the screen, because it stays exactly between the command and output. Don't be confused, because I'm mixing two problems here, `echo a` bug and format of the output ( for a single-line command ).

Also, the output for multiline commands could look like this ( the idea here is that **it should look like it was posted**, so new lines should not be removed ):
```
pwsh> echo a;
echo b;
echo c;
a
b
c
pwsh> echo a;
echo b;
echo c;
a
b
c

Here is the prompt
```

But the output for multiline commands is not critical, it still can stay like this and will not cause any issues:
```
pwsh> echo a; echo b; echo c;
a
b
c
pwsh> echo a; echo b; echo c;
a
b
c

Here is the prompt
```

**Comment by JanDeDobbeleer** [comment]
@silverqx @lisonge thx both for the elaborate explanation, I think I found a fix. At least, I could reproduce this on Windows and make it work. So 🤞🏻

**Comment by JanDeDobbeleer** [comment]
There's still a bug when you now type `;` in a single line. I'll have to find a better way to identify a multiline prompt. The only issue is that I have to manually replace that (which is error prone). So now, typing `echo ";"` or `echo a; echo b` will break things.

**Comment by silverqx** [comment]
@JanDeDobbeleer I see it:
```
command = strings.Replace(command, ";", fmt.Sprintf(";%s", e.ansi.newLine()), newlines)
```

How do you obtain the last executed command? Because as you wrote it is not a good idea to detect it, eg if I call multiline command and then:
```
λ Get-History | select -First 1 -ExpandProperty CommandLine
echo a;
echo b;
echo c;
```

Then PowerShell returns the last executed command already with new lines, maybe PSReadLine provides a better way to obtain the last executed command and you can avoid that buggy prone detection.

Ideal would be to obtain the last executed command in a format as it was posted to the terminal.

**Comment by JanDeDobbeleer** [comment]
You don't have access to that so you need to use [PsReadLine](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/init/omp.ps1#L208) which gives a single line string at that point in time. I haven't figured that out just yet, also, the behavior is different on Windows and iOS. So fixing one breaks the other a bit...

**Comment by JanDeDobbeleer** [comment]
@silverqx what could work is counting the [tokens](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.language.tokenkind?view=powershellsdk-1.1.0).

**Comment by silverqx** [comment]
I tried this now on windows:
```
Set-PSReadlineKeyHandler -Key Enter -ScriptBlock {
    $command = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$command, [ref]$cursor)
    $command | Add-Content -Path xyzz.txt
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
}
```

And executed command in `$command` variable already contains the correct string, on windows it contains `LF` unstriped. @JanDeDobbeleer

**Comment by silverqx** [comment]
I see how you do it, you are catching that command in `Enable-PoshTransientPrompt` and sending it to the `main.go::main()` where you dispatch it to the `renderTransientPrompt(*args.Command)`, something eats newlines 😁😂 @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
@silverqx seems like nothing is eating newlines and I'm just an idiot. Fix incoming. The fact that newlines did not do anything (I had to revert to ANSI powered newlines) threw me way off base.

**Pull request merged**
