### PR TITLE
fix(git): remove trailing space from upstream icons

### PR DESCRIPTION
**Pull request by jreilly-lukava**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

Removed the spaces as discussed in #4774.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by jreilly-lukava** [comment]
Looks like I missed some tests.  I'm not familiar with Go and don't have an environment setup.  I can work around this issue by overriding my icons.  Fix up this PR if you want or just close it.  Sorry, thanks for oh-my-posh!

**Comment by JanDeDobbeleer** [comment]
@jreilly-lukava you should be able to spin up a workspace to solve that swiftly in your fork.

**Comment by jreilly-lukava** [comment]
> @jreilly-lukava you should be able to spin up a workspace to solve that swiftly in your fork.

I forgot about that wizardry.  Hopefully I got it and all the tests will pass now.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @jreilly-lukava for code,doc

This is pure magic 🪄! @holopin-bot @jreilly-lukava wizard

**Pull request merged**
