### PR TITLE
Add 'Networks' segment (Windows only)

### PR DESCRIPTION
**Pull request by LNKLEO**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@LNKLEO what's the benefit of this one over the wifi segment?

**Comment by LNKLEO** [comment]
wifi segment only provide wifi network, my segment provide all networks, including wifi, cellular, wired network, even if a network over bluetooth.

image

besides above, it also able to identify FireWire 1394, DSL, etc. I just grouped them as 'other', for a low usage in personal area.

**Comment by JanDeDobbeleer** [comment]
@LNKLEO exactly, so the wifi segment is redundant in that case. I would remove the wifi segment in favor of a network segment.

**Comment by LNKLEO** [comment]
yes, you are right, I have removed wifi, and will maintenance network segment when need

**Comment by JanDeDobbeleer** [comment]
@LNKLEO the review is on my list when I get the time (as it larger, I will probably rework myself, so no need to keep rebasing).

**Comment by JanDeDobbeleer** [comment]
@LNKLEO I was trying to look at the actual code here to see how we could improve it as it's very inflexible (and complicated). I'm going to solve that challenge by creating multiple segments per connection type. This also allows for extensibility per platform.

**Comment by JanDeDobbeleer** [comment]
See #2857

**Pull request closed without merging**
