### PR TITLE
theme: add kali-wsl

### PR DESCRIPTION
**Pull request by playday3008**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines

### Description

Same as `kali.omp.json`, but colours identical to original Kali bash terminal in WSL, also changed `@` to `㉿` in non-root user
Also, (I don't know why, but) I change hard-coded `root` username to dynamic

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by playday3008** [comment]
Root:
image
Non-root:
image
(IDK why symbols is not displaying, so):
image

**Comment by lewis-yeung** [comment]
> IDK why symbols is not displaying

@playday3008 From [docs](https://ohmyposh.dev/docs/share):

> Some glyphs aren't rendered correctly, that's not you but the limitations of the renderer.

BTW, I like the cute skull 💀. 😆

**Comment by JanDeDobbeleer** [comment]
@playday3008 any reason why we're not adjusting the kali theme itself?

**Comment by playday3008** [comment]
> @playday3008 any reason why we're not adjusting the kali theme itself?

There is no important reason

**Comment by JanDeDobbeleer** [comment]
@playday3008 in that case I would adjust the current theme to reflect the real prompt. Makes it easier for people.

**Comment by playday3008** [comment]
> @playday3008 in that case I would adjust the current theme to reflect the real prompt. Makes it easier for people.

Ok, close PR after that)

**Pull request closed without merging**
