### PR TITLE
Add This new theme.

### PR DESCRIPTION
**Pull request by if-tea**
Please accept the request and add this newly beautiful theme to the repository. Thanks in advance. ✌

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@if-tea what's the difference with #1648?

**Comment by if-tea** [comment]
@JanDeDobbeleer I mistakenly added the image to my previous commit. That is why I committed for the second time. 🥰

**Comment by JanDeDobbeleer** [comment]
@if-tea can you migrate the theme to config version 1? You can update oh-my-posh and use `oh-my-posh --config if_tea.omp.json --migrate --write` and update this PR.

**Comment by JanDeDobbeleer** [comment]
@if-tea I did it for you, it does seem there's either an issue with the last block or something that's missing (the white hook at the start feels off)

**Comment by if-tea** [comment]
I am creating another theme. Will push very soon .

**Comment by JanDeDobbeleer** [comment]
@if-tea when merging this I need you agree we do this under MIT rather than GPL. If you would be so kind to acknowledge that, I can merge before #1807 goes in main.

**Comment by if-tea** [comment]
> @if-tea when merging this I need you agree we do this under MIT rather than GPL. If you would be so kind to acknowledge that, I can merge before #1807 goes in main.

Of course I agree.

**Pull request merged**
