### PR TITLE
Add more badges in README

### PR DESCRIPTION
**Pull request by Goooler**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### <samp>🤖 Generated by Copilot at 895cee4</samp>

The summary of the changes is:

[License](COPYING)
[PowerShell Gallery](https://www.powershellgallery.com/packages/oh-my-posh)
[HomeBrew](https://formulae.brew.sh/formula/oh-my-posh)
[Scoop](https://github.com/ScoopInstaller/Main/blob/master/bucket/oh-my-posh.json)

### <samp>🤖 Generated by Copilot at 895cee4</samp>

* Add badges for package managers to the README file ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3690/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R14-R16))

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by Goooler** [comment]
May need to remove the PowerShell Gallery badge, it's outdated.

**Comment by JanDeDobbeleer** [comment]
@Goooler only the license is correct, the Gallery is deprecated, and scoop and homebrew aren't our official installers.

**Comment by Goooler** [comment]
Yeah, but Shields only supports the official repos, I can drop them if you want.

**Comment by JanDeDobbeleer** [comment]
@Goooler yes, I dont mind adding the license 😃

**Comment by Goooler** [comment]
Done.

**Pull request merged**
