### PR TITLE
feat(windows): registry query segment

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

closes #1260

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by memcpy-rand-rand-rand** [comment]
@JanDeDobbeleer, thanks for the edits.  Still wrangling with merging myself, but noticed that the template call moved out of enabled()?  I believe this breaks the "if I fail to get the value from the registry display this instead" template scenario.

**Comment by JanDeDobbeleer** [comment]
@memcpy-rand-rand-rand ah yes, the fallback value. That was necessary in your case, right? Let me add that back! That means that we don't error but return a value of that's filled in.

**Comment by JanDeDobbeleer** [comment]
@memcpy-rand-rand-rand incoming via #1306

**Comment by memcpy-rand-rand-rand** [comment]
Actually, I had changed the logic away from the fallback value using the template.

It evaluated the template in IsEnabled() such that if the user had configured something in the config json to be displayed when '. Value' is null, the string to use for the segment would be non-empty and therefore segment enabled.  If no template or result of the template is empty then isenabled returned false.

**Comment by JanDeDobbeleer** [comment]
@memcpy-rand-rand-rand gotcha, looking at the case though it makes it easier to have that value directly and do some of the lifting for the end user. If that's OK with you.

**Comment by memcpy-rand-rand-rand** [comment]
sure thing, I like the explicit approach.  will have a play when I finally get my merging sorted out :)

**Pull request merged**
