### PR TITLE
feat(theme): add illusi0n theme

### PR DESCRIPTION
**Pull request by oguilhermegomes**

### CODE REVIEW

**Comment by oguilhermegomes** [comment]
@JanDeDobbeleer could you please check this PR?

**Comment by JanDeDobbeleer** [comment]
@guilhermelias do you have a screenshot?

**Comment by guilhermelias** [comment]
@JanDeDobbeleer yes, i have!
illusi0n

**Comment by guilhermelias** [comment]
With git repository
illusi0n

**Comment by oguilhermegomes** [comment]
@JanDeDobbeleer yes, i have!
illusi0n

**Pull request merged**
