### PR TITLE
chore: add .editorconfig

### PR DESCRIPTION
**Pull request by tillig**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

There was already some VS Code support but this little extra bit can make it easier to ensure contributors are using the established conventions for indentation and formatting; as well as setting up some additional testing/debugging support.

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
I like the `. editorconfig` addition, but I'm personally against adding editor specific configs to a repo.  Not everyone uses vscode, so `. editorconfig` will suffice.

**Comment by tillig** [comment]
Fair enough. There was already a .vscode folder in here so I figured adding to it wouldn't be an issue. Let me roll that back.

**Comment by tillig** [comment]
In case others are looking for a better VS Code experience, I was able to do it with a workspace file.

In the directory right above where you cloned `oh-my-posh3` create a JSON file called `oh-my-posh3.code-workspace` and put your tasks, etc. in there. There's a little oddness in that, with VS Code the `$GOPATH` can be inferred so it's not necessarily always in the environment, so `go build` needs to be directed a bit more specifically. I simply set mine to build in the parent folder since `.gitignore` here is generated and `oh-my-posh3` is, itself, not excluded.

Instead of opening VS Code in the actual oh-my-posh3 cloned folder, open the workspace and all the extra stuff will be available.

```json
{
  "folders": [
    {
      "path": "oh-my-posh3"
    }
  ],
  "launch": {
    "compounds": [
    ],
    "configurations": [
      {
        "args": [
          "-test.v"
        ],
        "mode": "test",
        "name": "Debug Tests",
        "program": "${workspaceFolder}",
        "request": "launch",
        "type": "go"
      },
      {
        "args": [
        ],
        "cwd": "${workspaceFolder}",
        "mode": "exec",
        "name": "Launch oh-my-posh",
        "preLaunchTask": "build",
        "program": "${workspaceFolder}/../oh-my-posh-exe",
        "request": "launch",
        "type": "go"
      }
    ]
  },
  "tasks": {
    "tasks": [
      {
        "args": [
          "build",
          "-o",
          "../oh-my-posh-exe"
        ],
        "options": {
          "cwd": "${workspaceFolder}"
        },
        "command": "go",
        "group": {
          "isDefault": true,
          "kind": "build"
        },
        "label": "build",
        "type": "shell"
      },
      {
        "args": [
          "test",
          "-v"
        ],
        "command": "go",
        "group": {
          "isDefault": true,
          "kind": "test"
        },
        "label": "test",
        "type": "shell"
      }
    ],
    "version": "2.0.0"
  }
}
```

**Comment by JanDeDobbeleer** [comment]
> There was already a .vscode folder in here

I'll have to remove that one then. Not ok :-)

> with VS Code the `$GOPATH` can be inferred

Good news, I just migrated to go modules so it doesn't matter where you clone the repo.

One last remark, I really don't like those `merge` commits, can you rebase on top of the latest master?
Feel free to also delete the `.vscode` folder.

**Comment by tillig** [comment]
OK, think I have it this time. I:

- rebased
- removed the existing .vscode stuff
- updated the commit message to be more accurate
- updated the PR title to reflect the new commit message

How's it looking?

**Comment by JanDeDobbeleer** [comment]
> How's it looking?

Puuuuurfect

**Pull request merged**
