### PR TITLE
fix(elvish): prevent cutting off a right-aligned block

### PR DESCRIPTION
**Pull request by lewis-yeung**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added/updated (for bug fixes / features).

### Description

In Elvish, a prompt line will always wrap when the cursor reaches the right-most cell on the terminal screen. We have to reduce the terminal width by 1 (just like the patch for the bleed bug in PowerShell) and use ANSI control sequences whenever we need a line feed (`\n`), so a right-aligned block will not be broken. BTW, the right prompt always works correctly because it's natively supported by the shell.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Review by JanDeDobbeleer — APPROVED** [review]

**Comment by JanDeDobbeleer** [comment]
Thanks for submitting a PR to the project!

In order to review and merge PRs most efficiently, we require that all PRs grant maintainer edit access before we review them. For information on how to do this, [see the documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by JanDeDobbeleer** [comment]
Thanks for submitting a PR to the project!

In order to review and merge PRs most efficiently, we require that all PRs grant maintainer edit access before we review them. For information on how to do this, [see the documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by lewis-yeung** [comment]
I have to rework this. The behavior of Elvish wrapping at the end of a prompt line is inconsistent across different platforms (tested on Windows and WSL). On WSL (maybe also regular Linux), the newline rendering of prompts in Elvish seems broken because of this change, but I haven't found the root cause yet. Further debugging/testing is needed. The shell-specific is somewhat tricky, but no worse than Tcsh which is weird in so many ways. 😅

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I wonder if we should keep supporting these shells though. They're nice and not really feature rich. I only added them for feature parity with starship, but they're actually terrible.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer We just keep basic support (at least for a primary prompt), which is not guaranteed to be full-featured. After all, the update frequency of feature support for a shell is positively correlated with its user base.

**Comment by lewis-yeung** [comment]
Follow-up work has been done in #5614.

**Pull request merged**
