### PR TITLE
feat(http): use proxy from environment for HTTP calls

### LINKED ISSUE #3897: oh-my-posh font install      failed to get nerd fonts release
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Try downloading fonts behind a proxy

### Theme

default

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

cmd

### Log output

```Shell
>oh-my-posh font install

    failed to get nerd fonts release
```

```
>oh-my-posh debug --plain

Version: 16.8.0

Shell: oh-my-posh

Segments:

ConsoleTitle(true)                        -   1 ms - oh-my-posh in alter
session(true)                             -   0 ms -  alter
path(true)                                -   1 ms -   ~
git(false)                                -  35 ms -
root(true)                                -   0 ms -  
exit(true)                                -   0 ms -  
node(false)                               -   0 ms -
go(false)                                 -   0 ms -
python(false)                             -   0 ms -
shell(true)                               -   0 ms - in oh-my-posh
time(true)                                -   0 ms - at 16:08:42

Run duration: 57.4257ms
```
```

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
feat(http): use proxy from environment for HTTP calls

resolves #3897

### CODE REVIEW

**Comment by chucklu** [comment]
@JanDeDobbeleer  How does this work? I have configured global proxy on win10, but it install font failed.

**Comment by chucklu** [comment]
also tried setx to configure proxy in windows terminal, still did not work
setx http_proxy "http://ip:port"
setx https_proxy "https://ip:port"

**Comment by JanDeDobbeleer** [comment]
> The function checks for the following environment variables, in order of precedence:
> - HTTP_PROXY or http_proxy: Used for HTTP requests.
> - HTTPS_PROXY or https_proxy: Used for HTTPS requests.
> - NO_PROXY or no_proxy: A comma-separated list of hosts that should bypass the proxy.

So this should word provided that these environment variables are present. I don't know why you'd use `setx` though, are you using `cmd`? In PowerShell: `$env:HTTPS_PROXY="https://ip:port/"`

**Comment by chucklu** [comment]
@JanDeDobbeleer 
1.Not sure how to configure the proxy in environment, I have tried to configure the proxy in environment variables of system. It does not work.

2.I am using Powershell, and tried your command `$env:HTTPS_PROXY="https://ip:port/`, it does not work, the cmd can not complete, and stuck in unfinished status. I have to ctrl+c to break it.

3.Then I tried `Set-Item -Path "Env:HTTPS_PROXY" -Value "https://ip:port"`, still did not work.

Do you have any verbose log for cmd like git command `GIT_TRACE=1 GCM_TRACE=1 git fetch origin`?  I would like to know the proxy value used for ` oh-my-posh font install`

**Comment by chucklu** [comment]
Or maybe you can provide a command like `git config --global http.proxy http://proxyUsername:proxyPassword@proxy.server.com:port`, explicitly configure the proxy manually.

**Comment by JanDeDobbeleer** [comment]
@chucklu there's no logging in that part, this all works magically via go's built-in system. Using zsh on my end this works like a charm:

image

**Comment by chucklu** [comment]
I  have downloaded the font file https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip, and tried to install it via fontforge patcher, but it  does not work.
And when I unzip Meslo.zip, there are 72 ttf font files, and if I want to install the font file manually.
 
 fontforge --script ./font-patcher --complete MesloLGSNerdFont-Regular.ttf
18 ttf file with regular, not sure which one to install? does it mean I need install all of them one by one, previously I install another font's single ttf file, but it does not work
image

**Comment by JanDeDobbeleer** [comment]
Good question, we install all ttf files.

**Comment by chucklu** [comment]
@JanDeDobbeleer   when I tried to manually install MesloLGSNerdFont-Regular.ttf, I got lots of warning or error like this:

> The glyph named ring is mapped to U+F07EB.
>   But its name indicates it should be mapped to U+02DA.

And when the installation for single ttf finished, the font does not listed at here Control Panel\All Control Panel Items\Fonts

**Comment by chucklu** [comment]
Finally I make it by font setting feature of win10 
1.unzip the fonts zip file
2.choose 72 ttf files in it
3.drag and drop it to install
image

terrible experience with fontforge, I suggest you add the drag and drop to install as an option in documentation

**Comment by chucklu** [comment]
I have also checked the installed fonts on computer with c# code
```c#
 [Test]
        public void Test2023_0704_001()
        {
            // Create an instance of InstalledFontCollection
            InstalledFontCollection installedFonts = new InstalledFontCollection();

            // Get the array of FontFamily objects representing the installed fonts
           System.Drawing.FontFamily[] fonts = installedFonts.Families;

            int index = 0;
            // Display the font names
            foreach (var font in fonts)
            {
                if (font.Name.Contains("Nerd"))
                {
                    index++;
                    Console.WriteLine($"{index:D3}, {font.Name}");
                }
            }
        }
```
001, MesloLGL Nerd Font
002, MesloLGL Nerd Font Mono
003, MesloLGL Nerd Font Propo
004, MesloLGLDZ Nerd Font
005, MesloLGLDZ Nerd Font Mono
006, MesloLGLDZ Nerd Font Propo
007, MesloLGM Nerd Font
008, MesloLGM Nerd Font Mono
009, MesloLGM Nerd Font Propo
010, MesloLGMDZ Nerd Font
011, MesloLGMDZ Nerd Font Mono
012, MesloLGMDZ Nerd Font Propo
013, MesloLGS Nerd Font
014, MesloLGS Nerd Font Mono
015, MesloLGS Nerd Font Propo
016, MesloLGSDZ Nerd Font
017, MesloLGSDZ Nerd Font Mono
018, MesloLGSDZ Nerd Font Propo

18 fonts with 72 ttf files, so each font with 4 ttf files
maybe we only need drag and drop 4 ttf files to install them, if we only need the `MesloLGM Nerd Font` font mentioned here https://ohmyposh.dev/docs/installation/fonts#configuration
Meslo\MesloLGMNerdFont-Bold.ttf
Meslo\MesloLGMNerdFont-BoldItalic.ttf
Meslo\MesloLGMNerdFont-Italic.ttf
Meslo\MesloLGMNerdFont-Regular.ttf

**Pull request merged**
