### PR TITLE
chore: adjust license to MIT

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

To be more accessible and allow people to reuse the code, I want to change the license from GPL to MIT.
According to legal practices, this requires approval of all contributors before this can happen.
Can you reply with "Agreed" so I can mark your name resolved? Thanks.
In case you object, feel free to do so here as well.

- [x] JanDeDobbeleer
- [x] lnu
- [x] TravisTX
- [x] memcpy-rand-rand-rand
- [x] cdonnellytx
- [x] asherber
- [x] tillig
- [x] Khaos66
- [x] NickCraver
- [x] sectorogo
- [x] wozjac
- [x] Jan0660
- [x] Mr-Vipi
- [x] evilz
- [x] mikesigs
- [x] stefanes
- [x] erclu
- [x] relativityhd
- [x] LarsBauer
- [x] icy-comet
- [x] lfelipe1501
- [x] LuiseFreese
- [x] TheTaylorLee
- [x] JustinGrote
- [x] mattwojo
- [x] Vixb1122
- [x] marcduiker
- [x] aexvir
- [x] Descalon
- [x] pratyushgguptaa
- [x] denelon
- [x] joshruggles
- [x] di4m0nds
- [x] gschizas
- [x] iarejenius
- [x] brian6932
- [x] hacst
- [x] billyrayxbox
- [x] jvsca
- [x] sdebruyn
- [x] jedwillick
- [x] ttyz
- [x] tjackadams
- [x] larserikfinholt
- [x] yehorb
- [x] hezhizhen
- [x] decart 
- [x] rfverbruggen 
- [x] jtracey93
- [x] Naccl
- [x] SeanKilleen
- [x] rushabhhere
- [x] julesrx
- [x] simorgh1
- [x] hanskokx
- [x] darkvertex
- [x] eltociear
- [x] mattcargile
- [x] maru-sama 
- [x] bewing 
- [x] justin-vogt
- [x] TedCrocker
- [x] shanselman 
- [x] hasancemcerit
- [x] HaroldPetersInskipp
- [x] Victoria-DR
- [x] jonnychipz
- [x] tomkerkhove
- [x] SagarYadav17
- [x] alchatti
- [x] AmRo045
- [x] patHyatt
- [x] erresen
- [x] mavaddat
- [x] jos3s
- [x] SebastianMineur 
- [x] markbullplus
- [x] xtoys
- [x] lydia7635
- [x] CapularisPerpetua
- [x] shiipou
- [x] FlavienMacquignon
- [x] bgelens
- [x] tiagaoalb
- [x] onpikono
- [x] UlanaXY
- [x] nwykes
- [x] shawnwildermuth
- [x] jbonnier

## Optional

- [ ] @th3c0d3br34ker (1)
- [ ] @kasuken (1)
- [ ] @tori4582 (1)
- [ ] @hgreving (1)
- [x] @qiansen1386 (UI user)
- [ ] @fantasyzhjk (UI user)
- [ ] @CorneliusTantius (UI user)
- [x] @Karsten7 (UI user)
- [ ] @PapiPeppers (UI user)

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by mikesigs** [comment]
Agreed

**Comment by erclu** [comment]
Agreed

**Comment by hacst** [comment]
Agreed

**Comment by aexvir** [comment]
so... if I get it correctly... this is relicensing as MIT? 🧐

**Comment by joshruggles** [comment]
Agreed

**Comment by lnu** [comment]
Agreed

**Comment by NickCraver** [comment]
Agreed :)

**Comment by aexvir** [comment]
agreed 🙂

**Comment by di4m0nds** [comment]
Agreed 👍

**Comment by iarejenius** [comment]
Agreed.

**Comment by icy-comet** [comment]
agreed +1

**Comment by tillig** [comment]
Agreed

**Comment by evilz** [comment]
Ok 👌

**Comment by relativityhd** [comment]
Agreed :)

**Comment by TheTaylorLee** [comment]
Agreed

**Comment by stefanes** [comment]
Agreed

**Comment by LuiseFreese** [comment]
Agreed 😍

**Comment by lfelipe1501** [comment]
Agreed

**Comment by Jan0660** [comment]
Agreed

**Comment by tradiff** [comment]
Agreed

**Comment by marcduiker** [comment]
Agreed

**Comment by Descalon** [comment]
Agreed

**Comment by asherber** [comment]
Agreed

**Comment by LarsBauer** [comment]
Agreed

**Comment by sectorogo** [comment]
Agreed

**Comment by memcpy-rand-rand-rand** [comment]
Agreed 👍

**Comment by denelon** [comment]
Agreed

**Comment by billyrayxbox** [comment]
Agreed 💪

**Comment by gschizas** [comment]
Agreed

**Comment by brian6932** [comment]
Agreed

**Comment by mattwojo** [comment]
Agreed.

**Comment by wozjac** [comment]
Agreed.

**Comment by jvsca** [comment]
Agreed

**Comment by JustinGrote** [comment]
Agreed

**Comment by Vixb1122** [comment]
Agreed

**Comment by cdonnellytx** [comment]
Agreed

**Comment by sdebruyn** [comment]
Agreed

**Comment by pratyushgguptaa** [comment]
Agreed

**Comment by jedwillick** [comment]
Agreed

**Comment by Khaos66** [comment]
Oc, agreed!

**Comment by Mr-Vipi** [comment]
Agreed

**Comment by tjackadams** [comment]
Agreed

**Comment by larserikfinholt** [comment]
Agreed

**Comment by evmoroz** [comment]
Agreed

**Comment by hezhizhen** [comment]
Agreed

**Comment by yehorb** [comment]
Agreed.

**Comment by SeanKilleen** [comment]
Agreed 👍

**Comment by simorgh1** [comment]
Agreed 👍

**Comment by hanskokx** [comment]
Agreed

**Comment by jtracey93** [comment]
Agreed

**Comment by julesrx** [comment]
Agreed

**Comment by rushabhhere** [comment]
Agreed 👍🏻

**Comment by rfverbruggen** [comment]
Agreed!

**Comment by darkvertex** [comment]
Agreed 👍

**Comment by decart** [comment]
Agreed

**Comment by Naccl** [comment]
Agreed

**Comment by mattcargile** [comment]
Agreed

**Comment by bewing** [comment]
Agreed

**Comment by eltociear** [comment]
Agreed

**Comment by maru-sama** [comment]
Fine for me.

**Comment by justin-vogt** [comment]
Agreed

**Comment by SagarYadav17** [comment]
Agreed

**Comment by alchatti** [comment]
Agreed

**Comment by AmRo045** [comment]
Agreed

**Comment by patHyatt** [comment]
Agreed

**Comment by mavaddat** [comment]
Agreed

**Comment by erresen** [comment]
Agreed

**Comment by HaroldPetersInskipp** [comment]
Agreed

**Comment by Victoria-DR** [comment]
Agreed

**Comment by TedCrocker** [comment]
Agreed

**Comment by jonnychipz** [comment]
Agreed

**Review by tomkerkhove — APPROVED** [review]
Agreed 🎉

**Comment by shanselman** [comment]
Agreed :shipit:

**Comment by hasancemcerit** [comment]
🤝 Agreed. Thanks👍🏻

**Comment by JanDeDobbeleer** [comment]
@nwykes @jos3s @bgelens @SebastianMineur you are the most important agreements I still need. The other maintainers aren't going to be a blocking factor. Just so we're in good shape to tackle 2022 💪🏻

**Comment by shiipou** [comment]
Agreed

**Comment by FlavienMacquignon** [comment]
Agreed

**Comment by SebastianMineur** [comment]
Agreed 🚀

**Comment by markbullplus** [comment]
Agreed&nbsp;



iPhoneMax


------------------ Original ------------------
From: Jan De Dobbeleer ***@***.***&gt;
Date: Sat,Feb 26,2022 3:21 AM
To: JanDeDobbeleer/oh-my-posh ***@***.***&gt;
Cc: markbull ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [JanDeDobbeleer/oh-my-posh] chore: adjust license (PR #1807)




Prerequisites
  
 I have read and understood the CONTRIBUTING guide 

 The commit message follows the conventional commits guidelines 

 Tests for the changes have been added (for bug fixes/features) 

 Docs have been added / updated (for bug fixes/features) 
 
Description
 
To be more accessible and allow people to reuse the code, I want to change the license.
 According to legal practices, this requires apporval of all contributors beofre this can happen.
 Can you reply with "Agreed" so I can mark your name resolved? Thanks.
 In case you object, feel free to do so here as well.
 
[ ] @JanDeDobbeleer
 [ ] @lnu
 [ ] @TravisTX
 [ ] @memcpy-rand-rand-rand
 [ ] @cdonnellytx
 [ ] @asherber
 [ ] @jos3s
 [ ] @nwykes
 [ ] @tillig
 [ ] @Khaos66
 [ ] @markbullplus
 [ ] @NickCraver
 [ ] @sectorogo
 [ ] @wozjac
 [ ] @Jan0660
 [ ] @shawnwildermuth
 [ ] @Mr-Vipi
 [ ] @evilz
 [ ] @mikesigs
 [ ] @stefanes
 [ ] @erclu
 [ ] @darkvertex
 [ ] @relativityhd
 [ ] @LarsBauer
 [ ] @icy-comet
 [ ] @lfelipe1501
 [ ] @tiagaoalb
 [ ] @LuiseFreese
 [ ] @TheTaylorLee
 [ ] @JustinGrote
 [ ] @mattwojo
 [ ] @Vixb1122
 [ ] @marcduiker
 [ ] @onpikono
 [ ] @aexvir
 [ ] @PapiPeppers
 [ ] @Descalon
 [ ] @jbonnier
 [ ] @pratyushgguptaa
 [ ] @qiansen1386
 [ ] @denelon
 [ ] @joshruggles
 [ ] @di4m0nds
 [ ] @gschizas
 [ ] @iarejenius
 [ ] @brian6932
 [ ] @th3c0d3br34ker
 [ ] @fantasyzhjk
 [ ] @hezhizhen
 [ ] @hacst
 [ ] @billyrayxbox
 [ ] @xtoys
 [ ] @CapularisPerpetua
 [ ] @justin-vogt
 [ ] @eltociear
 [ ] @patHyatt
 [ ] @bgelens
 [ ] @shiipou
 [ ] @HaroldPetersInskipp
 [ ] @hgreving
 [ ] @SeanKilleen
 [ ] @lydia7635
 [ ] @TedCrocker
 [ ] @rushabhhere
 [ ] @jtracey93
 [ ] @decart
 [ ] @mavaddat
 [ ] @kasuken
 [ ] @Victoria-DR
 [ ] @ttyz
 [ ] @tjackadams
 [ ] @simorgh1
 [ ] @jonnychipz
 [ ] @larserikfinholt
 [ ] @tomkerkhove
 [ ] @hanskokx
 [ ] @SagarYadav17
 [ ] @Karsten7
 [ ] @UlanaXY
 [ ] @yehorb
 [ ] @julesrx
 [ ] @shanselman
 [ ] @jvsca
 [ ] @alchatti
 [ ] @CorneliusTantius
 [ ] @tori4582
 [ ] @hasancemcerit
 [ ] @rfverbruggen
 [ ] @FlavienMacquignon
 [ ] @maru-sama
 [ ] @SebastianMineur
 [ ] @bewing
 [ ] @sdebruyn
 [ ] @AmRo045
 [ ] @mattcargile
 [ ] @jedwillick
 [ ] @Naccl
 [ ] @erresen
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/JanDeDobbeleer/oh-my-posh/pull/1807
 
Commit Summary
    
33ad481  chore: adjust license 
 
File Changes 
 
(2 files)
    
     M     .github/workflows/winget.yml     (16)      

     M     COPYING     (683)    
 
Patch Links:
    
https://github.com/JanDeDobbeleer/oh-my-posh/pull/1807.patch   

https://github.com/JanDeDobbeleer/oh-my-posh/pull/1807.diff 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by prokopto-dev** [comment]
Agreed

**Comment by jos3s** [comment]
Agreed

**Comment by lydia7635** [comment]
Agreed 👍

**Comment by xtoys** [comment]
Agreed

**Comment by bgelens** [comment]
Agreed

**Comment by Manthan-Kuber** [comment]
Agreed 👍

**Comment by UlanaXY** [comment]
Agreed

**Comment by tiagaoalb** [comment]
Agreed

**Comment by jbonnier** [comment]
Agreed

**Comment by onpikono** [comment]
Agreed.

**Comment by shawnwildermuth** [comment]
Agreed.

**Comment by tiwahu** [comment]
Agreed. #1801

**Comment by rfverbruggen** [comment]
Discovered that I'm not added to the all-contributors list

@all-contributors please add @rfverbruggen for code

**Comment by nwykes** [comment]
Agreed

**Comment by qiansen1386** [comment]
Agreed.

**Comment by Karsten7** [comment]
Agreed

**Pull request merged**
