### PR TITLE
feat: add gb carbon intensity segment

### PR DESCRIPTION
**Pull request by AlexJPotter**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### <samp>🤖 Generated by Copilot at 2e222df</samp>

This pull request adds a new segment type, `gbcarbonintensity`, to the oh-my-posh project. The segment displays the carbon intensity of the electricity grid in Great Britain, using data from an API. The pull request includes changes to the `engine` package, the JSON schema file, the unit tests, the segment implementation, the documentation, and the website sidebar.

### <samp>🤖 Generated by Copilot at 2e222df</samp>

*  Add a new segment type `GBCARBONINTENSITY` to display the GB carbon intensity data ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-cd158856c1b1aa6b2acece8041eb07352e4247b700e0fc62798a6be35d5f1c7dR143-R144), [link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-892c540c9bfebcb3bb8a0be1714201cd17eb6f0d40367c09f80d56e883b7335eR270))
*  Implement the `GbCarbonIntensity` struct and its methods in `src/segments/gb_carbon_intensity.go` ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-a77acd4f0484172c3bfe64b83171f98f8d0549f2d74098a34965d9be570cf14eR1-R166))
*  Add unit tests for the `GbCarbonIntensity` struct and its methods in `src/segments/gb_carbon_intensity_test.go` ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-8ea3c9c1edf78796b043f50199f3cbf5703442667dcbf0c389b30d72596ca419R1-R266))
*  Add a new entry to the `Segments` map to associate the segment type with the segment writer ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-cd158856c1b1aa6b2acece8041eb07352e4247b700e0fc62798a6be35d5f1c7dL258-R339))
*  Add a new conditional schema for the segment configuration in `themes/schema.json` ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-892c540c9bfebcb3bb8a0be1714201cd17eb6f0d40367c09f80d56e883b7335eR852-R876))
*  Add the documentation for the segment in `website/docs/segments/gbcarbonintensity.mdx` ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-0076d86ff519093be1d2c5e684349e9328ad62b417d83b3dba150344e7741461R1-R72))
*  Add the segment documentation page to the sidebar navigation in `website/sidebars.js` ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4396/files?diff=unified&w=0#diff-4caaf3187919c98f42856c140e32964b0829fc19165f3c989a6cd4ea088a7164R77))

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@AlexJPotter I would rename this to `CarbonIntensity` and add a disclaimer it's only supported for the UK for now. That way we can add other countries/regions as well without breaking changes. The implementation can stay UK specific, until we have other contributions/possibilities.

**Comment by AlexJPotter** [comment]
> @AlexJPotter I would rename this to `CarbonIntensity` and add a disclaimer it's only supported for the UK for now. That way we can add other countries/regions as well without breaking changes. The implementation can stay UK specific, until we have other contributions/possibilities.

Thanks for taking a look @JanDeDobbeleer - I've made the refactor and pushed the changes 😃

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @AlexJPotter for code,design,doc

This is pure magic 🪄! @holopin-bot @AlexJPotter wizard

**Comment by JanDeDobbeleer** [comment]
@AlexJPotter I refactored this a bit, so you'll have to adjust the template on your end of you added it instead of using the default.

**Comment by AlexJPotter** [comment]
Thanks @JanDeDobbeleer - looks great 😃

**Pull request merged**
