### PR TITLE
fix: foreground color admin icon

### PR DESCRIPTION
**Pull request by DaBasile**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

fix: foreground color admin icon
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@Goliaita the commits need to follow the conventional commit guidelines. In this case, something like `fix: foreground color admin icon`

**Review by DaBasile — COMMENTED** [review]
fix: foreground color admin icon

**Comment by JanDeDobbeleer** [comment]
@Goliaita if you need some help in doing this, I'm going to try to close some PR's later today. Just let me know.

**Comment by DaBasile** [comment]
Yes please, is my first commit in an open repos, I think I know what have to do but not sure how

**Comment by JanDeDobbeleer** [comment]
First, you need to edit your commit message. You can do this by using `git commit --amend`. This opens your editor where you can change the commit message. Next is pushing that change to your branch, as we're about to replace your existing commit with the its renamed counterpart, we need to force push: `git push --force`.

**Comment by JanDeDobbeleer** [comment]
Well done, I'm going to cherry pick this though as I see you've merged the latest main into it where we expect a rebase. But that's going to bring us too far.

**Pull request closed without merging**
