### PR TITLE
Revert "chore: bump softprops/action-gh-release from 2.1.0 to 2.2.0"

### LINKED ISSUE #6018: Release v24.13.0 failed due to the bug of softprops/action-gh-release
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The release failed due to the bug of softprops/action-gh-release.

- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v24.13.0
- https://github.com/JanDeDobbeleer/oh-my-posh/actions/runs/12330949675/job/34417136591

```
Run softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048
👩‍🏭 Creating new GitHub release for tag v24.13.0...
⬆️ Uploading version.txt...
⬆️ Uploading themes.zip...
⬆️ Uploading posh-windows-arm64.exe...
⬆️ Uploading posh-windows-amd64.exe...
⬆️ Uploading posh-windows-386.exe...
⬆️ Uploading posh-linux-arm64...
⬆️ Uploading posh-linux-arm...
⬆️ Uploading posh-linux-amd64...
⬆️ Uploading posh-linux-386...
⬆️ Uploading posh-freebsd-arm64...
⬆️ Uploading posh-freebsd-arm...
⬆️ Uploading posh-freebsd-amd64...
⬆️ Uploading posh-freebsd-386...
⬆️ Uploading posh-darwin-arm64...
⬆️ Uploading posh-darwin-amd64...
⬆️ Uploading install-x86.msi.sha256...
⬆️ Uploading install-x86.msi...
⬆️ Uploading install-x64.msi.sha256...
⬆️ Uploading install-x64.msi...
⬆️ Uploading install-arm64.msi.sha256...
⬆️ Uploading install-arm64.msi...
⬆️ Uploading checksums.txt.sig...
⬆️ Uploading checksums.txt...
Error: Request body length does not match content-length header
```

softprops/action-gh-release v2.2.0 has a known issue.

- https://github.com/softprops/action-gh-release/issues/556

It was updated by Dependabot.

- https://github.com/JanDeDobbeleer/oh-my-posh/pull/6001

### Theme

.

### What OS are you seeing the problem on?

_No response_

### Which shell are you using?

_No response_

### Log output

```Shell
.
```

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Close #6018

This reverts commit 85d2be23f529f86eb90382cec4be0ff90babb725.

The release failed due to the bug of softprops/action-gh-release.

- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v24.13.0
- https://github.com/JanDeDobbeleer/oh-my-posh/actions/runs/12330949675/job/34417136591

```
Run softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048
👩‍🏭 Creating new GitHub release for tag v24.13.0...
⬆️ Uploading version.txt...
⬆️ Uploading themes.zip...
⬆️ Uploading posh-windows-arm64.exe...
⬆️ Uploading posh-windows-amd64.exe...
⬆️ Uploading posh-windows-386.exe...
⬆️ Uploading posh-linux-arm64...
⬆️ Uploading posh-linux-arm...
⬆️ Uploading posh-linux-amd64...
⬆️ Uploading posh-linux-386...
⬆️ Uploading posh-freebsd-arm64...
⬆️ Uploading posh-freebsd-arm...
⬆️ Uploading posh-freebsd-amd64...
⬆️ Uploading posh-freebsd-386...
⬆️ Uploading posh-darwin-arm64...
⬆️ Uploading posh-darwin-amd64...
⬆️ Uploading install-x86.msi.sha256...
⬆️ Uploading install-x86.msi...
⬆️ Uploading install-x64.msi.sha256...
⬆️ Uploading install-x64.msi...
⬆️ Uploading install-arm64.msi.sha256...
⬆️ Uploading install-arm64.msi...
⬆️ Uploading checksums.txt.sig...
⬆️ Uploading checksums.txt...
Error: Request body length does not match content-length header
```

softprops/action-gh-release v2.2.0 has a known issue.

- https://github.com/softprops/action-gh-release/issues/556

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added/updated (for bug fixes / features).

### Description

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
This pr downgrades action-gh-release.
My concern is that Dependabot may update it to v2.2.0 again.
I usually use Renovate, so I'm not familiar with Dependabot.

**Comment by JanDeDobbeleer** [comment]
@suzuki-shunsuke it will update it for sure. Don't they have a fix ready to go for this? I can only look at this in the morning unfortunately.

**Comment by suzuki-shunsuke** [comment]
> Don't they have a fix ready to go for this?

- https://github.com/softprops/action-gh-release/issues/556

The issue is still open.
I can't find any work to resolve this issue.
The default branch hasn't been updated after releasing 2.2.0, there is no reply from maintainers, and there is no pr to resolve this issue.

`softprops/action-gh-release@v2` is pointing v2.0.9, not v2.2.0.

**Comment by suzuki-shunsuke** [comment]
752d2ac748feff787d6ef795716ab96fe2192578 I've updated Dependabot setting to ignore softprops/action-gh-release 2.2.0.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#example-disabling-version-updates-for-some-dependencies

I've confirmed the setting works well.

https://github.com/suzuki-shunsuke/test-dependabot/blob/5f6fe0773a12569a003c3e696929539ce76f4941/.github/dependabot.yml#L1-L11
https://github.com/suzuki-shunsuke/test-dependabot/actions/runs/12334016873/job/34423641417

```
updater | 2024/12/14 23:42:23 INFO <job_932709362> Checking if softprops/action-gh-release 2.1.0 needs updating
updater | 2024/12/14 23:42:23 INFO <job_932709362> Ignored versions:
2024/12/14 23:42:23 INFO <job_932709362>   2.2.0 - from .github/dependabot.yml
  proxy | 2024/12/14 23:42:23 [014] GET [https://github.com:443/softprops/action-gh-release.git/info/refs?service=git-upload-pack](https://github.com/softprops/action-gh-release.git/info/refs?service=git-upload-pack)
2024/12/14 23:42:23 [014] 200 [https://github.com:443/softprops/action-gh-release.git/info/refs?service=git-upload-pack](https://github.com/softprops/action-gh-release.git/info/refs?service=git-upload-pack)
updater | 2024/12/14 23:42:23 INFO <job_932709362> All updates for softprops/action-gh-release were ignored
```

**Pull request merged**
