### PR TITLE
fix(pwsh): remove clear line hack

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

relates to #65
closes #2345

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@tillig this could bring back #65 although I was unable to reproduce it.

**Comment by tillig** [comment]
I'll update and check it out. Thanks for the heads up!

**Comment by RFCreate** [comment]
The changes in this PR shouldn't break anything, I check with GitLens and the lines being removed where just added 4 days ago [here](https://github.com/JanDeDobbeleer/oh-my-posh/commit/f403db826f5d6f38a3a53acf147a0176325c3971). | | *(Edit: fail #2442)*

I might be wrong btw.

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate they were moved, not added ;-)

**Comment by tillig** [comment]
Wrapping issue is back

@JanDeDobbeleer It did, in fact, return.

PowerShell 7.2.5
iTerm2 3.4.15
MacOS Monterey 12.4

<details><summary>Click to see my theme.json</summary>

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "#000000",
          "foreground": "#ff0000",
          "powerline_symbol": "",
          "properties": {
            "always_enabled": false
          },
          "style": "powerline",
          "template": "[⌧ {{ if gt .Code 0 }} {{ .Meaning }}{{ else }}{{ end }}]",
          "type": "exit"
        },
        {
          "background": "#ff0000",
          "foreground": "#000000",
          "powerline_symbol": "",
          "properties": {
            "root_icon": "☠"
          },
          "style": "powerline",
          "template": "  ",
          "type": "root"
        },
        {
          "background": "#1f1f1f",
          "foreground": "#ffffff",
          "powerline_symbol": "",
          "style": "powerline",
          "template": " {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} ",
          "type": "session"
        },
        {
          "background": "#0000c0",
          "foreground": "#ffffff",
          "powerline_symbol": "",
          "properties": {
            "style": "short"
          },
          "style": "powerline",
          "template": "  {{ .Path }} ",
          "type": "path"
        },
        {
          "background": "#0077c2",
          "foreground": "#ffffff",
          "powerline_symbol": "",
          "style": "powerline",
          "template": "{{ if .Env.LOCATION_STACK_DEPTH }}  {{ .Env.LOCATION_STACK_DEPTH }} {{ end }}",
          "type": "text"
        },
        {
          "background": "#720dcf",
          "foreground": "#ffffff",
          "powerline_symbol": "",
          "style": "powerline",
          "template": "{{ if .Env.VSPROMPTVERSION }} ⌂ vs{{ .Env.VSPROMPTVERSION }} {{ end }}",
          "type": "text"
        },
        {
          "background": "#00ffff",
          "foreground": "#000000",
          "powerline_symbol": "",
          "properties": {
            "display_mode": "always",
            "home_enabled": true
          },
          "style": "powerline",
          "template": "  {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "dotnet"
        },
        {
          "background": "#ebcc34",
          "foreground": "#000000",
          "powerline_symbol": "",
          "style": "powerline",
          "template": " ⎈ {{ .Context }}{{ if .Namespace }} :: {{ .Namespace }}{{ end }} ",
          "type": "kubectl"
        },
        {
          "background": "#3493eb",
          "foreground": "#000000",
          "powerline_symbol": "",
          "style": "powerline",
          "template": " ﴃ {{ .Name }} ",
          "type": "az"
        },
        {
          "background": "#00cc00",
          "foreground": "#000000",
          "powerline_symbol": "",
          "properties": {
            "fetch_status": true
          },
          "style": "powerline",
          "template": " {{ .HEAD }} {{ .BranchStatus }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0}}  {{ .StashCount }}{{ end }}{{ if gt .WorktreeCount 0}}  {{ .WorktreeCount }}{{ end }} ",
          "type": "git"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "foreground": "#ffffff",
          "properties": {
            "time_format": "15:04"
          },
          "style": "plain",
          "template": "[{{ .CurrentDate | date .Format }}]",
          "type": "time"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "segments": [
        {
          "style": "plain",
          "template": " {{ .Name }}>",
          "type": "shell"
        }
      ],
      "type": "prompt"
    }
  ],
  "final_space": true,
  "version": 2
}
```

</details>

**Comment by JanDeDobbeleer** [comment]
@tillig lawd no 🥲. I guess that's a keeper then! Will revert.

**Pull request merged**
