### PR TITLE
fix(shell): network config cache fallback

### PR DESCRIPTION
**Pull request by randombenj**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added/updated (for bug fixes / features).

### Description

When running `oh-my-posh init SHELL http://example.com/config.yml` and the user does 
not have network connection, the default config is used, even though the config is cached locally.

This change fixes this and loads the cached config if it exists.

### How

If the network call fails and the config is already cached, this config is loaded.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by randombenj** [comment]
@JanDeDobbeleer Is the macos `golangci-lint` failure in any way related to this change, as the same command runs successfully on Windows and Linux and the error message doesn't seem to be related to any of these changes?

**Comment by JanDeDobbeleer** [comment]
@randombenj seems like their latest has an issue.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @randombenj for code

This is pure magic 🪄! @holopin-bot @randombenj wizard

**Comment by randombenj** [comment]
@JanDeDobbeleer thanks for the fast merge, super cool contributor experience! :tada:

**Comment by JanDeDobbeleer** [comment]
@randombenj thank you for the useful addition. Makes sense to do this, if I used remote configs more often, I'd have the same need at times.

**Pull request merged**
