### PR TITLE
Path segment: add support for template property

### PR DESCRIPTION
**Pull request by tylerbutler**
_I'm opening this as a draft to verify the approach and get feedback before I go too far._

### Prerequisites

Not all of these are done, but I'll complete them iteratively in the PR.

- [x] I have read and understood the `CONTRIBUTING` guide
- [ ] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes/features)

### Description

This PR adds support for a `template` property in the Path segment. See #885 for more context.

#### Template properties

The template receives the following properties:

These four properties contain the string values of the path with various styles:

- Full
- Folder
- Letter
- Mixed

The `style` property is ignored. Instead, the strings passed to the template take into account the other properties that affect how the styles are rendered. For example, this path configuration produces the following:

```json
{
  "type": "path",
  "style": "plain",
  "foreground": "#ffffff",
  "background": "#ff479c",
  "properties": {
    "style": "agnoster",
    "folder_separator_icon": ">",
    "template": "<b>{{ .Full }} {{ .Folder }} {{ .Letter }} {{ .Mixed }}</b>"
  }
}
```

image

These four properties contain icons (as strings):

- FolderSeparatorIcon
- HomeIcon
- FolderIcon
- WindowsRegistryIcon

#### Behavior notes

When the template property is provided, the `style` property is ignored since the strings for all styles are passed to the template. This is consistent with other segments that support a template property. It should also be backwards-compatible. Existing themes won't have a template property and thus will continue to work as they do today. Users can opt into the template by adding it to their theme.

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@tylerbutler good idea, I'll have a look tomorrow 👍🏻

**Comment by JanDeDobbeleer** [comment]
Rather than prepopulate every style, I would keep style as a property. That gives the option to only format the directory once, and we can expose that as `.Path` for example. It would also be a good idea to expose the actual path `.PWD` so there can be colouring options based on that value too.

**Comment by JanDeDobbeleer** [comment]
Just delivered it

**Comment by tylerbutler** [comment]
@JanDeDobbeleer Nice! Sorry I didn't get back to this PR quickly. I'm glad to see the feature make it in though! :)

**Pull request closed without merging**
