### PR TITLE
docs(macos): add MacPorts install instructions

### PR DESCRIPTION
**Pull request by herbygillot**
https://ports.macports.org/port/oh-my-posh/

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- `NA` Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@herbygillot I'm not in favour of adding means of installation that I don't control. Are you maintaining this one?

**Comment by herbygillot** [comment]
Yes, that's correct, I'm the maintainer for `oh-my-posh`'s port.

**Comment by JanDeDobbeleer** [comment]
In that case I'll gladly review! I'm probably just going to alter the PR to include that context.

**Comment by herbygillot** [comment]
> In that case I'll gladly review! I'm probably just going to alter the PR to include that context.

OK, no problem at all

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @herbygillot for doc

This is pure magic 🪄! @holopin-bot @herbygillot wizard

**Pull request merged**
