### PR TITLE
Resolve config path for `POSH_THEME` environment variable

### PR DESCRIPTION
**Pull request by thanhph111**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

I have a specific use case where I need to set `POSH_THEME` from the client when SSHing into a server (using `SendEnv`). Due to differences in operating systems, the path for `POSH_THEME` needs to utilize `~` as HOME. I noticed that a recent update broke this setup.

While it is not recommended to overwrite `POSH_THEME` as mentioned in [this discussion](https://github.com/JanDeDobbeleer/oh-my-posh/issues/5362#issuecomment-2254157084), it is currently the only method I have to change it on the fly. Therefore, I would like to attempt resolving the path in `POSH_THEME` similar to how it is handled with the `--config` flag.

By the way, thank you for creating such amazing software and for considering this change.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@thanhph111 this isn't how we can solve this. `POSH_THEME` isn't to be accessed, it's currently the only way we can avoid doing more than we need to as `init` will resolve it so we can reuse the actual path for every prompt generation. Why not provide your own environment variable you add to `init`?

EDIT: this is what we did before, and it saves a few milliseconds off the execution. And I don't want to sacrifice that again.

**Comment by JanDeDobbeleer** [comment]
@thanhph111 I realized this could be trickier than originally designed. What if I adjust the logic so `POSH_THEME` stays internal, but another environment variable can be leveraged for this use-case? As in, that one would always follow the same logic we have for the `--config` flag (and is documented).

I wanted to rename `POSH_THEME` to `POSH_CONFIG_PATH` anyways, and if we have a `POSH_CONFIG_PATH_OVERRIDE` that will solve your challenge (and others').

**Comment by thanhph111** [comment]
@JanDeDobbeleer That would be great. I think we can design the command to reflect changes in `POSH_CONFIG_PATH_OVERRIDE` with minimal updates, making it more efficient than rerunning `init --config`. The priority order could be `--config` > `POSH_CONFIG_PATH_OVERRIDE` > `POSH_CONFIG_PATH`.

However, if `POSH_CONFIG_PATH` is intended for internal use, I think it might confuse users who try to override it. To avoid this, we could consider resetting `POSH_CONFIG_PATH` in every iteration.

**Comment by JanDeDobbeleer** [comment]
@thanhph111 if we rename it to _POSH_CONFIG_PATH, we're good to go. That one implies internal.

**Pull request closed without merging**
