### PR TITLE
docs:Added source flag to winget installation

### PR DESCRIPTION
**Pull request by RFCreate**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

### Description

I decided to add the source flag (-s winget) to the installation, because maybe you don't want to be prompted with a sort of error message that asks you to sign an agreement with Microsoft to let them know your device location. I propose to remove this annoying prompt by adding the source flag to winget.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate I never got this popup, BUT I wouldn't silently remove it for end users. I feel everyone should be in the know.

**Comment by RFCreate** [comment]
@JanDeDobbeleer I agree with you, but shouldn't the command install the program just by running it, the prompt just breaks the flow making you read and sign things.

And most importantly, if you don't sign, the command will FAIL.

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate yes, but that's a winget thing. As such it has nothing to do with oh-my-posh.

**Comment by RFCreate** [comment]
Internet photo of the agreement:
internet msstore agreement

@JanDeDobbeleer Of course it is a winget thing, but that behavior can be avoided. Personally, I always use the --source flag because I don't want to sign the agreement.

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate still, this is something for the winget docs, not something we should be working around or documenting imho.

**Comment by RFCreate** [comment]
@JanDeDobbeleer this is the same thing you were referencing in this [discussion](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/2402).

You were referencing the winget source anyways in a discrete manner. What I say is that purposely point to the source that you want to install from, and based on your [answer](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/2402#discussioncomment-2924356) you want the source to be winget.

You could even revert back to the previous name, like this:

>winget install oh-my-posh -s winget

And it will work and no fail.  (personally I prefer Id names: `JanDeDobbeleer.OhMyPosh`)

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate you're right, but I needed to revert to JanDeDobbeleer.OhMyPosh which is better imho. So that would be perfect.

**Comment by RFCreate** [comment]
> @shyguyCreate you're right, but I needed to revert to JanDeDobbeleer.OhMyPosh which is better imho. So that would be perfect.

@JanDeDobbeleer Yes, I said that I prefer Id names.

Maybe I did not understand, but what would be perfect?

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate change it to:

```
winget install JanDeDobbeleer.OhMyPosh
```

There's no overlap using that id.

**Comment by RFCreate** [comment]
@JanDeDobbeleer the installation phase is already as you marked in the code.
>winget install JanDeDobbeleer.OhMyPosh

A change in the upgrade behavior will really suit for a commit.
```
winget upgrade JanDeDobbeleer.OhMyPosh
```
---
But I still recommend to use the source flag.
```
winget install JanDeDobbeleer.OhMyPosh -s winget
winget upgrade JanDeDobbeleer.OhMyPosh -s winget
```

**Review by JanDeDobbeleer — APPROVED** [review]

**Pull request merged**
