### PR TITLE
theme: add catppucin

### PR DESCRIPTION
**Pull request by IrwinJuice**
### Prerequisites

- [x] I have read and understood the contributing guide
- [x] The commit message follows the conventional commits guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

### Description

Catppuccin is a community-driven pastel theme that aims to be the middle ground between low and high contrast themes. It consists of 4 soothing warm palettes with 26 eye-candy colors each, perfect for coding, designing, and much more!

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@IrwinJuice this is interesting. Basically it's the same theme with a different [palette](https://ohmyposh.dev/docs/configuration/colors#palette), right?

**Comment by IrwinJuice** [comment]
@JanDeDobbeleer Yes, but one of theme Fat (catpussin.omp) and 4 Slim. You can see them here https://github.com/IrwinJuice/catppuccin.omp

**Comment by IrwinJuice** [comment]
In general, some of them are very similar, but different colors are used there

**Comment by pkazmier** [comment]
Another take on a catppuccin theme: https://github.com/JanDeDobbeleer/oh-my-posh/discussions/5578

**Pull request merged**
