### PR TITLE
Bug fixes, refactoring and documentation revision for supported shells

### PR DESCRIPTION
**Pull request by lewis-yeung**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes or features).
- [x] Docs have been added or updated (for bug fixes or features).

### Description

@JanDeDobbeleer Really a bunch of changes. Appreciate your patience in reviewing. :)

- Add quotes to the Tcsh `eval` commands mentioned in the documentation since they are required for the initialization to work.
- Add coding styles for Lua (basically just for the *omp.lua* file) to EditorConfig.
- Improve initialization for all supported shells by correcting string quoting and reorganizing initialization scripts (which also improves maintainability).
- Escape special characters correctly for a prompt in Tcsh.
- Hide deprecated/internal CLI subcommands and flags from help text. (Related: #2204)
- Pass a CLI flag (`--save-cache`) explicitly to tell the OMP engine to save updated cache to file.

About the change for cache saving: this is to eliminate any underlying side effects caused by unwanted cache update. Say, when running `oh-my-posh print primary` command manually for testing purposes during development, it's unnecessary and inappropriate to update the session cache. A case can be that the prompt count gets an unwanted (extra) increment of 1, and the update is saved to the cache file. That way the prompt count in the session is messed up.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung can you do me a favour and split this one commit into multiple? There's a lot going on here :-)

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I don't have a macOS environment to test some changes. Could you please do me a favor on macOS and check whether the right prompt in Elvish reaches the rightmost cell on the terminal screen?

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung it does

**Comment by lewis-yeung** [comment]
> it does

@JanDeDobbeleer Got it. Then I should provide a workaround for Elvish on non-Windows systems in another PR since this was merged just now.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung ah, next time mark it as draft in that case.

**Pull request merged**
