### PR TITLE
fix(http): correct logic for authentication header

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@lnu no idea what I was thinking at the time, this was a really weird implementation.

EDIT: I remember now, it was to avoid doing the token calls. But I'll refactor the cache logic out of the `do` function and reuse that in `Do` and `Oauth`.

**Comment by lnu** [comment]
I had a look this morning but no time for a clean fix.
Thanks.

**Comment by JanDeDobbeleer** [comment]
@lnu if you find a few minutes, can you validate these changes? I can't run the code on an iPad unfortunately 😅 No pressure, it's just that I won't merge unless validated functionally.

**Comment by lnu** [comment]
@JanDeDobbeleer first thing on my to-do list for tomorrow.

**Comment by lnu** [comment]
@JanDeDobbeleer  tested and LGTM: works fine with Strava(I can't test withings but no reasons it won't work).

**Pull request merged**
