### PR TITLE
Gomod path modifications

### PR DESCRIPTION
**Pull request by maxlandon**
Reopened from a clean branch. By the way, I was wandering why you are reluctant of those changes ? It is because of currently open issues/PR or something else ?

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@maxlandon all I want is the go.mod to stay in src, I was just crazy busy doing a refactor.

**Comment by maxlandon** [comment]
Ohhh ok !
Yes so that PR actually leaves the go.mod in `src/`, appends `src/` to its path declaration, and adapt the imports.

**Comment by JanDeDobbeleer** [comment]
@maxlandon allow me to review in the morning!

**Comment by maxlandon** [comment]
Yup no hurries, thanks a lot for everything!

**Comment by JanDeDobbeleer** [comment]
See #3319

**Pull request closed without merging**
