### PR TITLE
feat: windows arm support

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### Description

[Description of the change]

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by libewa** [comment]
pls merge! @lucloner solved it in #461

**Comment by JanDeDobbeleer** [comment]
@libewa this hasn't got an infrastructure to create a build that works just yet. While @lucloner 's build works, this one doesn't.

**Comment by lucloner** [comment]
> @libewa this hasn't got an infrastructure to create a build that works just yet. While @lucloner 's build works, this one doesn't.

take it easy. i just work out for windows arm. and the code would have a bit work for @JanDeDobbeleer . 
I pulled once and my script is not compatible.
I compiled is windows arm branch, not the latest one. it couldn't done.

 just leave the work to the master.
before that, we got the patch. 
 
the problem would solved sooner or later. 
be happier every day.

**Comment by JanDeDobbeleer** [comment]
@libewa @lucloner @patriksvensson I have a first build for native windows arm64 support using go1.17. Who can validate?

[oh-my-posh.exe.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7145657/oh-my-posh.exe.zip)

**Comment by Ash258** [comment]
Adding my few cents.
Seems pretty good from my quick test. Windows properly identify it is native binary

image

image

Binary is much faster:

image


Environment:

image

<details>
<summary>Manifest used for installation</summary>


```json
{
    "version": "dev",
    "description": "A prompt theme engine for any shell",
    "homepage": "https://ohmyposh.dev",
    "license": "GPL-3.0-only",
    "changelog": "https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v3.180.1",
    "architecture": {
        "arm64": {
            "url": [
                "https://github.com/JanDeDobbeleer/oh-my-posh/files/7145657/oh-my-posh.exe.zip",
                "https://raw.githubusercontent.com/Ash258/Scoop-Ash258/main/support/oh-my-posh/Ash258.json"
            ],
            "hash": [
                "a54ea86a665bf8119a4534f6b6feb8bec378b7c974a740c3c8f2896499929dd3",
                "af5fa4864736479f1b462ecd33380bc7b5b7c99173108b59e99a6c06b7d477a6"
            ]
        }
    },
    "post_install": [
        "try { Get-Command 'Test-Persistence' -ErrorAction 'Stop' | Out-Null } catch { error 'Shovel flavour of scoop is required'; exit 258 }",
        "Move-Item \"$dir\\Ash258.json\" \"$dir\\themes\\Ash258.omp.json\" -Force",
        "if ($env:POSH_INSTALL) { # TODO: Migrate to install options",
        "    Write-UserMessage 'Installing Ash258 theme to $PROFILE' -Warning",
        "    $c = @(",
        "        '#region Oh-my-posh'",
        "        '$bitness = if ([System.IntPtr]::Size -eq 8) { ''64bit'' } else { ''32bit'' }'",
        "        '$ps = if ($PSVersionTable.PSVersion.Major -ge 6) { ''pwsh'' } else { ''ps'' }'",
        "        '$ps += ''@'' + $PSVersionTable.PSVersion.ToString()'",
        "        '$env:__SHELL_INFORMATION_POSH_258__ = \"$ps@$bitness\"'",
        "        \"Invoke-Expression (@(oh-my-posh.exe --print-init --shell 'pwsh' --config '$dir\\themes\\Ash258.omp.json') -join \"\"``n\"\")\"",
        "        'Enable-PoshTransientPrompt'",
        "        '#endregion Oh-my-posh'",
        "    )",
        "    $prof = if ($global) { $PROFILE.AllUsersAllHosts } else { $PROFILE }",
        "    New-Item $prof -ErrorAction 'SilentlyContinue' -Force | Out-Null",
        "    Add-Content $prof $c -Force",
        "}"
    ],
    "bin": [
        [
            "oh-my-posh.exe",
            "ohm"
        ]
    ],
    "persist": "themes",
    "checkver": {
        "github": "https://github.com/JanDeDobbeleer/oh-my-posh"
    },
    "autoupdate": {
        "changelog": "https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v$version",
        "architecture": {
            "64bit": {
                "url": "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v$version/posh-windows-wsl-amd64.7z"
            }
        },
        "hash": {
            "url": "$url.sha256"
        }
    }
}

```

</details>

**Comment by JanDeDobbeleer** [comment]
@Ash258 thank you so much! This is the first build that works out of the box. I guess I can add this to the supported architectures in that case.

**Comment by Ash258** [comment]
I would wait a bit for other tests from the above-mentioned guys. I will test a little more with more themes/segments to cover the potential edge cases. Architecture-specific issues are not expected as with go1.17 other tools (caddy, traefik, eksctl) work as expected on arm64 windows

**Comment by patriksvensson** [comment]
Happy to try it out this weekend

**Comment by Ash258** [comment]
I would consider it really stable. All the segments I use are working fine. Cannot test battery and similar, but if you have any special segment to test feel free to ping me.

- Windows 11, Raspberry pi 4B, Windows Terminal Stable 1.10.2383.0
- Executables in image:
     - `C:\ProgramData\Shovel\apps\oh-my-posh` is amd64 latest version
     - `C:\Users\Cosi ARM\Shovel\apps\ohm` is arm64 dev version from comment above

<details>
<summary>All available themes (no language specific segments)</summary>

image

image

All themes native arm binary: 33 seconds
All themes native amd64 emulated: 46 seconds

</details>

<details>
<summary>Language specific</summary>

nodejs
go
python

</details>

**Pull request merged**
