### PR TITLE
docs: YAML/TOML

### PR DESCRIPTION
**Pull request by ehawman-rosenberg**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- N/A Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

Added YAML/TOML info to the docs/installation/customize page, and sample code blocks on a few pages under docs/configuration. Also, pointed more explicitly from docs/installation/customize to docs/configuration/overview.

Currently, I am unable to preview my changes since I don't know how to tell VSCode (or rather, the  [MDX Preview extension](https://marketplace.visualstudio.com/items?itemName=xyc.vscode-mdx-preview)) how to import from `@theme/Tabs` and `@theme/TabItem`.

When trying to open MDX Preview on customize.mdx:
```
Cannot find module '@theme/TabItem'
Require stack:
- e:\Documents\Programming\oh-my-posh\website\docs\installation\noop.js
```

I mention this because the pages with Tabs are crying about unexpected tokens inside code blocks. I believe this is because it isn't properly recognizing the code block on my end. Hopefully it looks fine on yours.

When trying to open the MDX Preview on overview.mdx:
```
unknown: Unexpected token, expected "}" (48:11)

  46 | ```json
  47 | {
> 48 |   "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
     |            ^
  49 |   "final_space": true,
  50 |   "blocks": [
  51 |     {
```

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer I'm riding the strugglebus on this one. I added tabs to some files which (I think) necessitated renaming files from `.md` to `.mdx`. This has caused conflicts that I'm unable to rectify here on GitHub and I haven't been able to puzzle out on GitKraken.

At this point would it be best to just start a new branch and manually work my changes back in, or is there some way to salvage this pull request?

EDIT: Furthermore, would it just make sense to rename all files from `.md` to `.mdx` so that this functionality is standardized across the project?

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg I'll see if I can fix it 😬

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer if you take #2374 then I'll just rebuild this from scratch no problem. I think it would be better to jump to `mdx` all at once rather than bump into this problem each time we want to add `jsx` functionality to a `md` file.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg done

**Comment by ehawman-rosenberg** [comment]
See #2378

**Pull request closed without merging**
