### PR TITLE
refactor(theme): update multiverse-neon

### PR DESCRIPTION
**Pull request by garysassano**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added/updated (for bug fixes / features).

### Description

This PR includes the following changes:
- Replaces the generic yarn icon with the actual logo.
- Adds the generic pnpm icon (the actual logo is currently unavailable).
- Updates the icon colors to match the official brand colors.

The brand colors were extracted from the official SVG logos:
- [pnpm logo](https://pnpm.io/logos#standard-logo)
- [npm logo](https://github.com/npm/logos/blob/master/npm%20logo/npm-logo-red.svg)
- [yarn logo](https://github.com/yarnpkg/assets/blob/master/yarn-kitten.svg)
- [node logo](https://nodejs.org/static/logos/jsIconGreen.svg)

The colors were then adjusted to 90% brightness using the HSB color model.

Tips:

If you're not comfortable with working with Git,
we're working a guide (https://ohmyposh.dev/docs/contributing/git) to help you out.
Oh My Posh advises GitKraken (https://www.gitkraken.com/invite/nQmDPR9D) as your preferred cross platform Git GUI power tool.

-->

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@garysassano please adjust the commit message, it's not according to the required format.

**Comment by JanDeDobbeleer** [comment]
@garysassano changing the title isn't the same as the commit message, you can find a guide [here](https://ohmyposh.dev/docs/contributing/git#i-didnt-stick-to-the-conventional-commit-guidelines).

**Comment by garysassano** [comment]
Apologies, I wrongly assumed you would use a squash and merge strategy with `PR_TITLE`  as the commit message.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @garysassano for design

This is pure magic 🪄! @holopin-bot @garysassano wizard

**Pull request merged**
