### PR TITLE
feat(theme): add nu4a

### PR DESCRIPTION
**Pull request by sectorogo**
Hi all.

I have created this theme recently. I will be glad if you kindly accept it in your repo.

Best regards.

### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

Added new theme "nu4a". It's based on Agnoster, but with the following changes:
- execution time on the right side of the prompt
- error indicator was reworked and made flame like ball with Windows logo inside on the right side of the prompt
- changed the colors a bit

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@sectorogo thx for your contribution! I would love to merge this, can you reword your commit to follow the guidelines? `feat(theme): add nu4a`

**Comment by sectorogo** [comment]
> @sectorogo thx for your contribution! I would love to merge this, can you reword your commit to follow the guidelines? `feat(theme): add nu4a`

Sorry, this was my first commit ever. I have changed the title, is it Ok now?

**Comment by JanDeDobbeleer** [comment]
Alright. Let's see how we can facilitate this. A few questions, how did you create this commit? Via CLI, Github web interface or another way?

**Comment by sectorogo** [comment]
> Alright. Let's see how we can facilitate this. A few questions, how did you create this commit? Via CLI, Github web interface or another way?

I have created this with the GitHub web interface.

**Comment by JanDeDobbeleer** [comment]
@sectorogo teaching the difference between git and GitHub would bring me too far here. But it's a good idea to facilitate a session like that once!

**Pull request closed without merging**
