### PR TITLE
feat(python): Make the feature from commit-7da84d4 of PR-4400 optional

### PR DESCRIPTION
**Pull request by rockyoung**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

While it is undisputed that "venv" or ".venv" is commonly used as the name for virtual environments in most cases, it doesn't directly imply the desire for displaying the parent directory name as the virtual environment name. Some projects may have more than one virtual environment, such as ".venv", ".venv-test", ".venv-whatever", especially when testing across different Python and dependency versions. In such cases, if a user attempts to switch between these environments, they might find that when switching to ".venv", it displays the project name instead of the expected virtual environment name, causing confusion.

Additionally, considering Conda environments, where the default environment name is "base," it seems that pull-4400 hasn't taken into account the scenario with Conda. Assuming we display the parent directory even when the Conda "base" environment is activated, how do we distinguish whether the current environment is activated under Conda's "base" or ".venv"?

Moreover, when upgrading from older versions, users might find that their previously correct configurations and accustomed display methods have changed, leading sensitive users (like myself) to immediately think of configuration compatibility issues caused by the upgrade.

Therefore, considering all these factors, making this feature an optional Property configuration option with default settings disabled seems to be the best approach for ensuring maximum backward compatibility for our ❤️oh-my-posh❤️ while also catering to specific needs.

### How

Add a `use_parent_folder_4venv` property for python segment:
 - update code in 'src/segments/python.go' and 'src/segments/python_test.go';
 - update doc description in 'website/docs/segments/python.mdx'

check the commited source code for details.

### CODE REVIEW

**Review by rockyoung — COMMENTED** [review]
everything looks fine!

**Comment by JanDeDobbeleer** [comment]
@rockyoung I'm reviewing this later today! Probably will adjust a few things, but thanks!

**Comment by rockyoung** [comment]
@JanDeDobbeleer looks like you've been quite busy lately 😂, if possible, could leave a msg indicating what adjustments are needed, and i can make the changes and submit another PR afterward.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @rockyoung for code,doc

This is pure magic 🪄! @holopin-bot @rockyoung wizard

**Comment by bhuynhdev** [comment]
Thanks everyone for the amazing work, but for some reason `folder_name_fallback: false` is not working for me. Using WSL on Ubuntu; just installed the latest version today with the `curl` command. I am using the `atomic` theme with just one small adjustment to the Python segment:

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "version": 2,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "shell",
          "style": "diamond",
          "foreground": "#ffffff",
          "background": "#0077c2",
          "leading_diamond": "\u256d\u2500\ue0b6",
          "template": "\uf120 {{ .Name }} "
        },
        {
          "type": "root",
          "style": "diamond",
          "foreground": "#FFFB38",
          "background": "#ef5350",
          "template": "<parentBackground>\ue0b0</> \uf292 "
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\ue0b0",
          "foreground": "#2d3436",
          "background": "#FF9248",
          "template": " \uf07b\uea9c {{ .Path }} ",
          "properties": {
            "folder_icon": " \uf07b ",
            "home_icon": "\ue617",
            "style": "folder"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\ue0b0",
          "foreground": "#011627",
          "background": "#FFFB38",
          "background_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}",
            "{{ if gt .Ahead 0 }}#C792EA{{ end }}",
            "{{ if gt .Behind 0 }}#C792EA{{ end }}"
          ],
          "template": " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350> \uf046 {{ .Staging.String }}</>{{ end }} ",
          "properties": {
            "branch_icon": "\ue725 ",
            "fetch_status": true,
            "fetch_upstream_icon": true
          }
        },
        {
          "type": "executiontime",
          "style": "diamond",
          "foreground": "#ffffff",
          "background": "#83769c",
          "trailing_diamond": "\ue0b4",
          "template": " \ueba2 {{ .FormattedMs }}\u2800",
          "properties": {
            "style": "roundrock",
            "threshold": 0
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "node",
          "style": "diamond",
          "foreground": "#3C873A",
          "background": "#303030",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}",
          "properties": {
            "fetch_package_manager": true,
            "npm_icon": " <#cc3a3a>\ue5fa</> ",
            "yarn_icon": " <#348cba>\ue6a7</>"
          }
        },
        {
          "type": "python",
          "style": "diamond",
          "foreground": "#FFE873",
          "background": "#306998",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "folder_name_fallback": false,
          "template": "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
        },
        {
          "type": "java",
          "style": "diamond",
          "foreground": "#ffffff",
          "background": "#0e8ac8",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "dotnet",
          "style": "diamond",
          "foreground": "#0d6da8",
          "background": "#0e0e0e",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue77f {{ if .Unsupported }}\uf071{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "go",
          "style": "diamond",
          "foreground": "#06aad5",
          "background": "#ffffff",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "rust",
          "style": "diamond",
          "foreground": "#925837",
          "background": "#f3f0ec",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "dart",
          "style": "diamond",
          "foreground": "#055b9c",
          "background": "#e1e8e9",
          "leading_diamond": " \ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue798 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "angular",
          "style": "diamond",
          "foreground": "#ce092f",
          "background": "#ffffff",
          "leading_diamond": " \ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue753 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "nx",
          "style": "diamond",
          "foreground": "#ffffff",
          "background": "#1e293b",
          "leading_diamond": " \ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}"
        },
        {
          "type": "julia",
          "style": "diamond",
          "foreground": "#359a25",
          "background": "#945bb3",
          "leading_diamond": " \ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "<#ca3c34>\ue624</> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "ruby",
          "style": "diamond",
          "foreground": "#9c1006",
          "background": "#ffffff",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "azfunc",
          "style": "diamond",
          "foreground": "#5398c2",
          "background": "#ffffff",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4 ",
          "template": "\uf104<#f5bf45>\uf0e7</>\uf105 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        },
        {
          "type": "kubectl",
          "style": "diamond",
          "foreground": "#ffffff",
          "background": "#316ce4",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4",
          "template": "\uf308 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}"
        },
        {
          "type": "battery",
          "style": "powerline",
          "powerline_symbol": "\ue0b2",
          "invert_powerline": true,
          "foreground": "#262626",
          "background": "#f36943",
          "background_templates": [
            "{{if eq \"Charging\" .State.String}}#b8e994{{end}}",
            "{{if eq \"Discharging\" .State.String}}#fff34e{{end}}",
            "{{if eq \"Full\" .State.String}}#33DD2D{{end}}"
          ],
          "template": " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 ",
          "properties": {
            "charged_icon": "\uf240 ",
            "charging_icon": "\uf1e6 ",
            "discharging_icon": "\ue234 "
          }
        },
        {
          "type": "time",
          "style": "diamond",
          "invert_powerline": true,
          "foreground": "#ffffff",
          "background": "#40c4ff",
          "leading_diamond": "\ue0b2",
          "trailing_diamond": "\ue0b4",
          "template": " \uf073 {{ .CurrentDate | date .Format }} ",
          "properties": {
            "time_format": "Jan _2,15:04"
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#21c7c7",
          "template": "\u2570\u2500"
        },
        {
          "type": "status",
          "style": "plain",
          "foreground": "#e0f8ff",
          "foreground_templates": [
            "{{ if gt .Code 0 }}#ef5350{{ end }}"
          ],
          "template": "\ue285\ueab6 ",
          "properties": {
            "always_enabled": true
          }
        }
      ],
      "newline": true
    }
  ]
}
```

image

**Comment by JanDeDobbeleer** [comment]
@bhuynhdev you need to add it inside the `properties` object within the `segment`. Now you added it directly in the `segment`.

**Comment by bhuynhdev** [comment]
I knew it. The library works flawlessly it's me who are dumb. Thanks for the lightning fast response. My issue is fixed now.

**Pull request merged**
