### PR TITLE
feat(path): add 'max_depth' option for 'agnoster_short'

### PR DESCRIPTION
**Pull request by SebastianMineur**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

Added a new style for the path segment, almost like Agnoster Short but only shortens the number of folders exceeding `max_depth`.

Not sure if `Shortened` is the best possible name for it, but it's the best I could think of.

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
Looking at the almost identical styles, wouldn't it make sense to add that switch (max_depth) to Agnoster? If it resolves to anything <= 0 it behaves like Agnoster now.

**Comment by SebastianMineur** [comment]
Yeah, you're probably right. I was hesitant to alter the functionality of the classic Agnoster, but if I have your blessing.. 🙂
So default for max_depth will be 0, which will leave it working as before.

**Comment by SebastianMineur** [comment]
Ok, I moved the functionality into Agnoster Short. Made `max_depth` default to 1 instead, because there should always be at least one folder displayed at the end, but anything less behaves the same.

**Review by JanDeDobbeleer — APPROVED** [review]

**Comment by JanDeDobbeleer** [comment]
@NervousNerve fails on the linter. Can you check and adjust?

```
Running [/home/runner/golangci-lint-1.42.0-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=src] in [/home/runner/work/oh-my-posh/oh-my-posh/src] ...
69
  Error: File is not `gofmt`-ed with `-s` (gofmt)
70
  Error: line is 184 characters (lll)
71
  Error: line is 185 characters (lll)
72
  Error: line is 186 characters (lll)
73
  
74
  Error: issues found
75
  Ran golangci-lint in 31742ms
```

**Comment by SebastianMineur** [comment]
Forgot about gofmt, so that should be fixed now.
I tried running the linter locally, but it just complains about a bunch of stuff I didn't touch, so I don't know what that's about.
```
config.go:73:2: undeclared name: `config` (typecheck)
        config.AddDriver(yaml.Driver)
        ^
config.go:74:2: undeclared name: `config` (typecheck)
        config.AddDriver(json.Driver)
        ^
config.go:75:2: undeclared name: `config` (typecheck)
        config.AddDriver(toml.Driver)
        ^
template.go:51:43: undeclared name: `sprig` (typecheck)
        tmpl, err := template.New("title").Funcs(sprig.TxtFuncMap()).Parse(t.Template)
                                                 ^
console_title_test.go:57:7: env.On undefined (type *MockedEnvironment has no field or method On) (typecheck)
                env.On("getcwd", nil).Return(tc.Cwd)
                    ^
console_title_test.go:58:7: env.On undefined (type *MockedEnvironment has no field or method On) (typecheck)
                env.On("homeDir", nil).Return("/usr/home")
                    ^
console_title_test.go:59:7: env.On undefined (type *MockedEnvironment has no field or method On) (typecheck)
                env.On("getPathSeperator", nil).Return(tc.PathSeperator)
                    ^
segment_git_test.go:132:4: m.On undefined (type *MockedEnvironment has no field or method On) (typecheck)
        m.On("runCommand", "git", args).Return(returnValue, nil)
          ^
segment_path_test.go:18:14: env.Called undefined (type *MockedEnvironment has no field or method Called) (typecheck)
        args := env.Called(key)
                    ^
segment_path_test.go:23:14: env.Called undefined (type *MockedEnvironment has no field or method Called) (typecheck)
        args := env.Called(nil)
                    ^
segment_path_test.go:28:14: env.Called undefined (type *MockedEnvironment has no field or method Called) (typecheck)
        args := env.Called(nil)
                    ^
config.go:14:2: "github.com/gookit/config/v2" imported but not used (typecheck)
        "github.com/gookit/config/v2"
        ^
main.go:11:2: "github.com/gookit/config/v2" imported but not used (typecheck)
        "github.com/gookit/config/v2"
        ^
template.go:10:2: "github.com/Masterminds/sprig/v3" imported but not used (typecheck)
        "github.com/Masterminds/sprig/v3"
        ^
segment_path_test.go:7:2: "github.com/gookit/config/v2" imported but not used (typecheck)
        "github.com/gookit/config/v2"
        ^
../../../../../../usr/local/go/src/runtime/cgo/cgo.go:34:8: could not import C (cgo preprocessing failed) (typecheck)
import "C"
       ^
```

**Comment by JanDeDobbeleer** [comment]
@NervousNerve do you have all dependencies locally (running go test or go build should resolves that).

**Comment by SebastianMineur** [comment]
@JanDeDobbeleer Thank you for your help and patience. That was indeed the issue. I didn't have gcc installed.
Linter was complaining about long lines in my test cases, which should be fixed now.

**Pull request merged**
