### PR TITLE
fix(shell): wrap path with single quotes

### PR DESCRIPTION
**Pull request by lewis-yeung**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines

### Description

This may fix errors occur in specific cases where there are spaces in the OMP executable path.

<details><summary>Example of an error in fish</summary>

Run:

```fish
"/home/myname/o m p/oh-my-posh" init fish | source
```

Output:

```
/home/myname/o: command not found
- (line 28): 
    /home/myname/o m p/oh-my-posh print primary --config $POSH_THEME --shell fish --error $omp_status_cache --execution-time $omp_duration --stack-count $omp_stack_count --shell-version $FISH_VERSION
    ^
in function 'fish_prompt'
in command substitution
/home/myname/o: command not found
- (line 45): 
    /home/myname/o m p/oh-my-posh print right --config $POSH_THEME --shell fish --error $omp_status_cache --execution-time $omp_duration --stack-count $omp_stack_count --shell-version $FISH_VERSION
    ^
in function 'fish_right_prompt'
in command substitution
```

</details>

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung why a draft?

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I just think of other possible special characters included in the executable path. Since they are shell-specific, I have no idea if we should handle all special cases.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung from past experience, only spaces are an issue in UTF8 enabled shells. Which we assume. So if this works, let's ship it.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer OK. I'm gonna use single quotes instead and do that in init scripts for other shells.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer Almost done but I'm not able to test `omp.lua` for CMD for the time being. Could you please check and make any necessary fixes for it (if needed)? 🙏

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung CMD is fine, I fixed that specifically a while ago. Did you validate all shells?

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer Testing and fixing...

**Review by JanDeDobbeleer — APPROVED** [review]

**Comment by lewis-yeung** [comment]
**P.S.** Since OMP may support more shells in the future, maybe one day, we can find a way to refactor the logic of escaping and to make it centralized and easier to maintain. Well, at least for now it mostly works. ✅

**Pull request merged**
