### PR TITLE
theme(cloud-native-azure): show clock icon

### PR DESCRIPTION
**Pull request by BoseSj**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description
Updated line 99 to add the clock icon at the left of the time. 

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by BoseSj** [comment]
# Output

### Before Change
-_pwsh_
image
 
-_zsh_
image

### After Change
-_pwsh_
image

-_zsh_
image

# Conclusion
Feel free to suggest any edit. TY 😄

**Comment by JanDeDobbeleer** [comment]
This is only allowed by the theme authors.

**Comment by BoseSj** [comment]
@JanDeDobbeleer Can you please reopen this PR, so that I can ask for approval from the theme authors? 😄

**Comment by JanDeDobbeleer** [comment]
@tomkerkhove review wanted ;-)

**Review by tomkerkhove — APPROVED** [review]
LGTM

**Pull request merged**
