### PR TITLE
feat(scoop): Add POSH_THEMES_PATH environment variable

### PR DESCRIPTION
**Pull request by ralish**
### Prerequisites

- [X] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [X] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [X] Docs have been added/updated (for bug fixes/features)

### Description

Adds support for setting the `POSH_THEMES_PATH` environment variable when installing with `scoop`.

### CODE REVIEW

**Review by JanDeDobbeleer — APPROVED** [review]

**Comment by ralish** [comment]
@JanDeDobbeleer Could you please help me with what's required on the commit message. I think it might be incorrectly flagging the all-caps environment variable name?

**Comment by JanDeDobbeleer** [comment]
@ralish it starts with a capital

```
input: feat(scoop): Add POSH_THEMES_PATH environment variable
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
```

**Comment by ralish** [comment]
Thanks @JanDeDobbeleer!

**Comment by JanDeDobbeleer** [comment]
@All-contributors please add @ralish for code

**Comment by JanDeDobbeleer** [comment]
Ah. Damn. Need to adjust that path 😂

**Comment by JanDeDobbeleer** [comment]
https://github.com/all-contributors please add @ralish for code

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @ralish for code

**Pull request merged**
