### PR TITLE
Add support for Julia projects

### PR DESCRIPTION
**Pull request by davidanthoff**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

I'm trying to add support for Julia project files (these are either `Project.toml` or much less commonly `JuliaProject.toml` files). This PR doesn't seem to work, but I'm not sure what else I would have to do?

I'll add tests and docs once the code is working.

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@davidanthoff I added the tests, and it does work on my end using the [docs config](https://ohmyposh.dev/docs/segments/project#sample-configuration).

image

**Comment by davidanthoff** [comment]
Ah, cool! I might well have had a mistake in how I tested it, this is the first go programming I've ever done :)

I added a small doc update commit as well now.

And just to confirm one thing: this all works if a project file is missing a `version` element, right? That is valid in Julia, and from looking at the code and the test that seems to be the case, but then my go knowledge is kind of not there, so want to make sure I'm understanding this correctly.

**Comment by JanDeDobbeleer** [comment]
@davidanthoff yes!

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @davidanthoff for code,doc

**Pull request merged**
