### PR TITLE
Update customize.mdx

### PR DESCRIPTION
**Pull request by mavaddat**
Update the Lua for the cmd config so it uses the env var `POSH_THEMES_PATH` set by `oh-my-posh.exe`.

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

Updated the `oh-my-posh.lua` so that it uses the environment variable `POSH_THEMES_PATH` which is set my `oh-my-posh`.

### How

Using `os.getenv(POSH_THEMES_PATH")` as in 

```lua
load(io.popen('oh-my-posh init cmd --config ' .. os.getenv("POSH_THEMES_PATH") .. '/jandedobbeleer.omp.json'):read("*a"))()
```

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@mavaddat there are two commits in here and they should both respect the conventional commit guidelines. I'll review first as the change in the install script is interesting. I don't see why we would support older PowerShell versions in 2023.

**Comment by mavaddat** [comment]
> @mavaddat there are two commits in here and they should both respect the conventional commit guidelines.

Yes, I was going to come back and update the commit messages to comply with the Conventional Commit style. Sorry about my do-first-then-fix contribution approach... 😳 I am updating the commits now.

> I'll review first as the change in the install script is interesting. I don't see why we would support older PowerShell versions in 2023.

Some of us (e.g., _me_) are locked into enterprise version freeze environments where we cannot install or update our Powershell.

**Comment by JanDeDobbeleer** [comment]
@mavaddat gotcha, I'll try to review tomorrow, could be I adjust and merge myself.

**Comment by JanDeDobbeleer** [comment]
@mavaddat see #3724. As for the change in the docs, that's not a valid one. It clearly states we're dealing with a local file and not the theme's folder.

**Pull request closed without merging**
