### PR TITLE
feat(dotnettarget): add dotnettarget segment

### LINKED ISSUE #1568: Enhance dotnet segment to support .Net framework
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Enhance the dotnet segment to recognize if the folder contains a .Net framework project vs a dotnet core project.

Some suggestions are on the discussion such as parsing the project files and looking at the TargetFrameworkVersion element. 

I don't see an easy way to do this if only the .sln file is in the folder however, perhaps drilling into one of the projects in the solution and looking at that.

### PR DESCRIPTION
**Pull request by babieiev**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

This PR adds a new segment to display the target .NET framework version moniker (TFM) of the current project.

Resolves #1568

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@lesfiddler I can sure help. I'll try to go through it tomorrow. There's a few PR'a I need to help with.

**Comment by babieiev** [comment]
@JanDeDobbeleer The problem is solved. I added tests and updated the pull request.

**Comment by JanDeDobbeleer** [comment]
@lesfiddler thanks, now what I would do (and this is a refactor on your end I suppose), is also extend the `language` struct [like the dotnet segment](https://github.com/JanDeDobbeleer/oh-my-posh/blob/fed2d020256f19bf54c5094afc5a680bbe32a2a9/src/segments/dotnet.go#L10). That way you get a lof of things out of the box, and you can extend it with a `getVersion` function to extract the `TFM`, just like you already do. The python segment has an [example](https://github.com/JanDeDobbeleer/oh-my-posh/blob/fed2d020256f19bf54c5094afc5a680bbe32a2a9/src/segments/python.go#L38) for this. I'm still wondering if we should extend the `dotnet` segment with this one (first in the array), rather than set up a new segment. If a TFM is found, take that one, if not proceed with the dotnet CLI.

**Comment by babieiev** [comment]
@JanDeDobbeleer I'm also hesitant to add a new segment. I suggested this because it seems to me that this approach is just easier to understand. There is a certain difference between this and all other `language` segments. `TFM` is not the same as version. Let me explain. The moniker can look like `net7.0`, `netcoreapp3.1`, `net6.0-ios15.0`, and in some cases (although quite rarely), like `uap10.0` for example. If the `dotnet` segment shows the version of the active SDK, then my segment shows which framework the current project is targeting.
Of course, we can extend `language` struct, but I'm not sure that combining these two segments (`dotnet` and `dotnet_target`) is a good idea. But of course you are the maintainer, so the final decision is yours.
I'm a little busy right now, but soon I'll try to make the changes you ask for.

**Comment by JanDeDobbeleer** [comment]
@lesfiddler you're right, this is the same as [project](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segments/project.go) however, not dotnet. We should be able to extend that one.

**Comment by babieiev** [comment]
Oh! It's a wonder I didn't notice it sooner. [Project](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segments/project.go) segment is exactly what is needed, thanks.

**Comment by babieiev** [comment]
@JanDeDobbeleer `dotnet` project files can have 3 extensions: `*.csproj`, `*.vbproj` and `*.fsproj`. But `project.go` is not designed for multiple files. I am not sure that completely changing the structure, and accordingly the work, is a good decision. So, if we want to keep it as part of the `project.go`, I suggest separating them with a semicolon, like here:

New (multiple files):
```go
...
{
	Name:    "dotnet",
	File:    "*.csproj;*.vbproj;*.fsproj",
	Fetcher: n.getDotnetProject,
},
...

func (n *Project) hasProjectFile(p *ProjectItem) bool {
	files := strings.Split(p.File, ";")
	for _, file := range files {
		if n.env.HasFiles(file) {
			return true
		}
	}
	return false;
}
```

Old (single file):
```go
...
{
	Name:    "dotnet",
	File:    "*.csproj",
	Fetcher: n.getDotnetProject,
},
...

func (n *Project) hasProjectFile(p *ProjectItem) bool {
	return n.env.HasFiles(p.File)
}
```
Is that ok, or would you suggest something better?

**Comment by JanDeDobbeleer** [comment]
@lesfiddler I would change File to an array. Cleaner, and only internal anyways.

**Comment by babieiev** [comment]
@JanDeDobbeleer I've created a new branch for this change, so I'll open [a new PR](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3019) and close this one.

**Pull request closed without merging**
