### PR TITLE
Remove deprecated testing extensions from suggested VSCode extensions

### PR DESCRIPTION
**Pull request by darkvertex**
I have some other contributions coming but as I was preparing my repo for it, I noticed it was proposing deprecated VSCode extensions, so here's my first mini PR.

### Prerequisites

- [X] I have read and understood the `CONTRIBUTING` guide
- [X] The commit message follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines

### Description

In VSCode 1.59, a generic API and UI [**was officially added**](https://code.visualstudio.com/updates/v1_59#_testing-apis) for running tests, which provides all the functionality of the [_Test Explorer_](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) extension and more, so that extension became deprecated.

In the same vein, the popular [_Go Test Explorer_](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.vscode-go-test-adapter) extension is also deprecated as the [official Go language extension](https://marketplace.visualstudio.com/items?itemName=golang.Go) [**implemented the testing API**](https://github.com/golang/vscode-go/issues/1579#issuecomment-899963390) back in August.

### CODE REVIEW

**Comment by lnu** [comment]
Deprecated but debugging a unit test works only in the nigthly version(golang.go-nightly). We should wait until the nightly is released on the regular extension. Thanks for the pr.

**Comment by darkvertex** [comment]
> Deprecated but debugging a unit test works only in the nigthly version(golang.go-nightly). We should wait until the nightly is released on the regular extension. Thanks for the pr.

Ah! I did not know this. Thanks for pointing it out.

Indeed, let's wait til that change is released properly to the stable channel.

**Comment by lnu** [comment]
Go extension has been updated to 0.29 and everything works as before(with debug).

And don't forget to rename your commit to something like:
`chore: vscode recommended extensions update`

**Comment by JanDeDobbeleer** [comment]
@darkvertex @lnu can we merge this in now?

**Comment by lnu** [comment]
> @darkvertex @lnu can we merge this in now?

Yes it can be merged. Only the commit message has to be fixed

**Comment by darkvertex** [comment]
Sorry I didn't get around to editing the commit message before you merged it. — I'll be more mindful of the commit message styling in future contributions.

**Pull request merged**
