### PR TITLE
theme: added new theme Pure

### PR DESCRIPTION
**Pull request by sky96111**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

[Description of the change]

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by lnu** [comment]
You can rewrite your commit as
`theme: added new theme Pure`  to pass the commit lint check.
And add a new line at the end of the file to pass the linter.

**Comment by lnu** [comment]
Almost there: the first commit is still causing an issue. You can squash and reword to have a single commit with the right text.

**Comment by sky96111** [comment]
> Almost there: the first commit is still causing an issue. You can squash and reword to have a single commit with the right text.

Sorry, I can't understand. Do you mean that I should close the PR and open with another commit with a proper name?

**Comment by lnu** [comment]
You don't need to close it. You just have to do a squash rebase. 
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Pull request closed without merging**
