### PR TITLE
feat(posh-git): parse environment variable

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

Removes the posh-git segment but allows the user to leverage the posh-git output just like the regular git segment.
This is a breaking change.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
The `git` segment still references the now deleted `posh-git` segment.

image

For me it's also unclear how I can tell oh-my-posh to use the posh-git output 🤔

**Comment by JanDeDobbeleer** [comment]
@eXpl0it3r what do you mean with output? All you need to do is set the environment variable and we will use posh-git to display git data. The change is that now we will use the raw data instead of the rendered string, which allows you to leverage (almost all) features a regular segment and the git segment has.

That link should point to posh-git so I'll fix that. Thanks!

**Comment by eXpl0it3r** [comment]
Note: It's two links in that box.

Well previously I used in the theme config the following:

```
        {
          "background": "#0077c2",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "style": "powerline",
          "type": "poshgit"
        },
```

And I got the posh-git string (or similar, don't have screenshot at hand from before):
image

Now when I change the type to `git` I get:
image

Also I've set `$env:POSH_GIT_ENABLED = $true`
So how do I get the default posh-git output?

**Comment by eXpl0it3r** [comment]
I guess this is about as close as I can get with the `git` config.

```
        {
          "foreground": "#FFFF00",
          "style": "plain",
          "type": "git",
          "template": "[<#00FFFF>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}</> <#008000>+{{ .Staging.Added }} ~{{ .Staging.Modified }} -{{ .Staging.Deleted }}</> | <#C00000>+{{ .Working.Added }} ~{{ .Working.Modified }} -{{ .Working.Deleted }}</>]"
        },
```

Not sure how to get "Conflicted files", "There are unstaged changes in the working tree" or "There are uncommitted changes i.e. staged changes in the working tree waiting to be committed" as mentioned in the [posh-git readme](https://github.com/dahlbyk/posh-git#git-status-summary-information).

But let me know if there's a way to actually get posh-git's output to show, I'm just rather used to it. 😄

**Comment by JanDeDobbeleer** [comment]
@eXpl0it3r see [this](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/2773?sort=top#discussioncomment-3635809) answer.

**Comment by eXpl0it3r** [comment]
Woho, this works, thanks! 🥳 

Do you think, this could be added to the info box about posh-git on the git page?

**Pull request merged**
