### PR TITLE
Connections

### LINKED ISSUE #2700: Considering support more network interface
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hope omp could support cellular network and cable networks, and hava a variable to identify which network is currently in use.

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

Replace wifi with connections.
Resolves #2700

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@LNKLEO the first commit works, the second I can't validate on my VM. Can you have a look?

**Comment by LNKLEO** [comment]
> @LNKLEO the first commit works, the second I can't validate on my VM. Can you have a look?
image
maybe you have just missed a "style" property, and I found you don't specific a default style or process a segment without a style in a writer.

I have made a PR to fix, see and try this. #2882

**Comment by JanDeDobbeleer** [comment]
@LNKLEO style is a required field, but if we do go to a default I would make that the same as Plain and Powerline. But this code works, right?

**Comment by LNKLEO** [comment]
@JanDeDobbeleer Yes, it works well like above.
write only type and style to profile, run on latest connection branch code, and add "WiFi" to default template to make block more clear

**Pull request merged**
