### PR TITLE
Added a new theme.

### PR DESCRIPTION
**Pull request by if-tea**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [] Tests for the changes have been added (for bug fixes/features)
- [] Docs have been added / updated (for bug fixes/features)

### Description
Uploaded a new theme 1_shell. Hope everyone will love it.

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@if-tea I'd allow the update to if_tea, but adding two additional themes might be a stretch :-) You will need to update this to v2.

**Comment by if-tea** [comment]
Add this item. This theme is very beautiful.

**Comment by JanDeDobbeleer** [comment]
@if-tea please remove the abundant themes, you added 3, I'm not sure if this was intentional or not as the names are very confusing.

**Comment by if-tea** [comment]
Alright

**Pull request closed without merging**
