### PR TITLE
feat(init): remote config

### LINKED ISSUE #1803: Pull Set-PoshPrompt directly from gist
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I've been playing with gists, and I was wondering if OMP could alter Set-PoshPrompt to accept JSON directly.

My initial thought was something like this:

`myprofile.ps1`
``` powershell
$PoshResponse = Invoke-Webrequest -Uri "https://gist.githubusercontent.com/myusername/mygistid/raw/myfileid/myfile.omp.json"
Set-PoshPrompt -Theme $PoshResponse.Content
```

`oh-my-posh.psm1`
``` powershell
function Set-PoshPrompt {
    ...
    if (Test-JSON $Theme) {
        Out-File -FilePath "$($env:POSH_THEMES_PATH)/gist-theme.omp.json" -InputObject $Theme -Force
        $Theme = "gist-theme"
    }

    $config = ""
    ...
```

The result would be the creation/overwriting of a gist-theme theme file, which is then loaded via the normal flow. 

Before I bother making a pull request, does this seem like something you'd be interested in? Are there consequences to this that I am not considering?

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

resolves #1803 

This change allows to initialise the prompt with a remote config that is stored locally per session.
We can decide to no longer ship the themes based on this as it's pretty straightforward to get started that way.

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by ehawman-rosenberg** [comment]
Is this intended to be used like 

``` powershell
oh-my-posh --init --shell pwsh --config "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/jandedobbeleer.omp.json" | Invoke-Expression
```

Because that currently isn't working for me.

**Comment by ehawman-rosenberg** [comment]
More specifically: It either loads this
image

Or, if I already have one loaded the conventional way (referencing a local json), it silently fails
image

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg did you update and restart your shell? You need to restart the session as it doesn't reload on the fly like you did. That's not possible as the init can only run once on shell start.

**Comment by ehawman-rosenberg** [comment]
Yes. I have this line in my profile.ps1 file (changed to bubbles so that we can't get confused by the default)

``` ps
oh-my-posh --init --shell pwsh --config "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/bubbles.omp.json" | Invoke-Expression
```

Opening a new Windows Terminal instance still results in this 
image

**Comment by JanDeDobbeleer** [comment]
Can you double check the version of oh-my-posh? `oh-my-posh --version`

**Comment by ehawman-rosenberg** [comment]
Well that be my problem. I was using Get-InstalledModule to validate, which I guess was looking at the wrong module dir. Tested and working! I'll shut up now :)

**Pull request merged**
