### PR TITLE
docs: update docs for time format.

### PR DESCRIPTION
**Pull request by riazXrazor**
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] N/A Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

update docs for time format, added more go standard time and date formats  and predefined date and timestamp format constants in file segment-time.md

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@riazXrazor great work, can you reword you commit to comply with the conventional commit guidelines?

**Comment by riazXrazor** [comment]
@JanDeDobbeleer i updated it

**Comment by JanDeDobbeleer** [comment]
Good, now instead of merging master into your branch I'll need you tondo a rebase. Do you have all the knowledge you need to do that or shall I assist?

**Comment by riazXrazor** [comment]
a little assist would be helpful ;-)

**Comment by JanDeDobbeleer** [comment]
@riazXrazor I cherry picked your change into main 👍🏻

**Comment by riazXrazor** [comment]
@JanDeDobbeleer cool thanks

**Pull request closed without merging**
