### PR TITLE
git template

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

Introduces templating functionality for the git segment.
As this can eventually resolve into removing quite a bit of switches, we can decide to do a major increment (BREAKING CHANGE)
or keep the "old way" supported but no longer offer support.

- refactor(git): add template capabilities
- refactor(git): allow status in template
- refactor(git): add upstream icon to repo
- refactor(git): add branch status to template
- refactor(git): move deprecated functions

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
@lnu thoughts?

**Comment by lnu** [comment]
since it's a big change, should the original git_segment be kept(and marked obsolete) and a new one created?  
Lots of people are using omp for the git segment and maybe don't need the extra tweaks.

**Comment by JanDeDobbeleer** [comment]
> since it's a big change, should the original git_segment be kept(and marked obsolete) and a new one created?
> Lots of people are using omp for the git segment and maybe don't need the extra tweaks.

Ah yes, that's why I did not delete anything. This still works just like you would expect (and the code is separate). So basically, unless we delete the `deprecated` files, that will never stop working.

**Comment by JanDeDobbeleer** [comment]
I only need to update the themes. Colors can all move to color templates but that needs a bit of attention (and I'm tired right now ;-))

**Comment by JanDeDobbeleer** [comment]
@lnu would LOVE your eyes on this. Everything has been tested (automatically and manually). Basically, current implementations will still work, all themes have been adjusted and when using a `template` this will result in the new logic being used. The docs have been updated so new themes should not follow old standards.

**Comment by JanDeDobbeleer** [comment]
For reference, `.jan.omp.json` is the current main theme file and the other one is the new, updated theme file from this PR.

image

**Comment by lnu** [comment]
check list(wip - deprecated followed by template):

- [x] not git directory 
image
- [x] no changes
image
- [x] 1 untracked file
image
- [x] 1 staged file
image
- [x] 1 untracked + git reset --soft HEAD~1
image
- [x] 1 stash
image
- [x] detached(git checkout sha1)
image
image
- [x] Worktree **(missing entry in schema.json `fetch_worktree_count`)**
image
- [x] 1 commit ahead
image
- [x] 4 commits behind
image
- [x] branch max length 5
image
- [x] 1 modified file
image

**Comment by JanDeDobbeleer** [comment]
@lnu about ahead and behind, colors are enabled? I didn't really adjust that part, only moved the code. Might have been broken already?

**Comment by lnu** [comment]
> @lnu about ahead and behind, colors are enabled? I didn't really adjust that part, only moved the code. Might have been broken already?

I have a hard time setting the background color with `background_tempates`, it always get the default background.  
it works for modified files but not when behind or ahead.

**Comment by JanDeDobbeleer** [comment]
> I have a hard time setting the background color with `background_tempates`, it always get the default background

Could it be because there's a typo in `background_tempates` -> `background_templates`? I did those tests and it does work on my machine.™️ Can you share the segments? I'll debug and see what happens.

**Comment by lnu** [comment]
```
{
  //"$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "$schema": "file:d:/dev/temp/oh-my-posh/themes/schema.json",
  //"$schema": "file:/Volumes/data/dev/temp/oh-my-posh/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#193549",
          "background": "#fffb38",
          "properties": {
            "display_worktree_count": true,
            "display_stash_count": true,
            "display_upstream_icon": true,
            "status_colors_enabled": true,
            "local_changes_color": "#ff9248",
            "ahead_and_behind_color": "#f26d50",
            "behind_color": "#f17c37",
            "ahead_color": "#89d1dc",
            "stash_count_icon": "\uF692 "
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#fffb38",
          "background_templates": [
            "{{ if or (.Repo.Working.Changed) (.Repo.Staging.Changed) }}#B388FF{{ end }}",
            "{{ if and (.Repo.Ahead gt 0) (.Repo.Behind gt 0) }}#ff4500{{ end }}",
            "{{ if .Repo.Ahead gt 0 }}#89d1dc{{ end }}",
            "{{ if .Repo.Behind gt 0 }}#f17c37{{ end }}"
          ],
          "leading_diamond": "",
          "trailing_diamond": "",
          "properties": {
            "fetch_status": true,
            "fetch_stash_count": true,
            "fetch_upstream_icon": true,
            "fetch_worktree_count": true,
            "branch_max_length": 25,
            "template": "{{ .Repo.UpstreamIcon }}{{ .Repo.HEAD }}{{ .Repo.BranchStatus }}{{ if .Repo.Working.Changed }} \uF044 {{ .Repo.Working.String }}{{ end }}{{ if and (.Repo.Working.Changed) (.Repo.Staging.Changed) }} |{{ end }}{{ if .Repo.Staging.Changed }} \uF046 {{ .Repo.Staging.String }}{{ end }}{{ if gt .Repo.StashCount 0 }} \uF692 {{ .Repo.StashCount }}{{ end }}{{ if gt .Repo.WorktreeCount 0 }} \uf1bb {{ .Repo.WorktreeCount }}{{ end }}"
          }
        }
      ],
      "type": "prompt"
    }
  ],
  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{if .Root}} ⚡ {{end}}{{.Folder | replace \"~\" \"🏚\" }}@{{.Host}}",
  "final_space": true,
  "osc99": false
}
```

looks like an error parsing the background_templates

**Comment by JanDeDobbeleer** [comment]
@lnu it's me. The templates are wrong, this works:

```json
"background_templates": [
    "{{ if or (.Repo.Working.Changed) (.Repo.Staging.Changed) }}#f36943{{ end }}",
    "{{ if and (gt .Repo.Ahead 0) (gt .Repo.Behind 0) }}#a8216b{{ end }}",
    "{{ if gt .Repo.Ahead 0 }}#35b5ff{{ end }}",
    "{{ if gt .Repo.Behind 0 }}#f89cfa{{ end }}"
],
```

I'll adjust the themes 🤦🏻

**Comment by lnu** [comment]
and I think we should do this:
```
func (g *git) getGitCommandOutput(args ...string) string {
	args = append([]string{"-C", strings.TrimSuffix(g.Repo.gitRootFolder, ".git"), "--no-optional-locks", "-c", "core.quotepath=false", "-c", "color.status=false"}, args...)
	val, _ := g.env.runCommand(g.getGitCommand(), args...)
	return val
}
```

If you want to test a specific folder with `--pwd`, the git segment does not respect the path.(ie. testing in vscode)

**Comment by lnu** [comment]
> @lnu it's me. The templates are wrong, this works:
> 
> ```json
> "background_templates": [
>     "{{ if or (.Repo.Working.Changed) (.Repo.Staging.Changed) }}#f36943{{ end }}",
>     "{{ if and (gt .Repo.Ahead 0) (gt .Repo.Behind 0) }}#a8216b{{ end }}",
>     "{{ if gt .Repo.Ahead 0 }}#35b5ff{{ end }}",
>     "{{ if gt .Repo.Behind 0 }}#f89cfa{{ end }}"
> ],
> ```
> 
> I'll adjust the themes 🤦🏻

everything seems to work with the changes.

**Comment by JanDeDobbeleer** [comment]
You can now also do this, which is fricking amazing:

```json
{
  "type": "git",
  "style": "powerline",
  "foreground": "#193549",
  "foreground_templates": [
    "{{ if and (gt .Repo.Ahead 0) (gt .Repo.Behind 0) }}#ffffff{{ end }}"
  ],
  "background": "#2e9599",
  "background_templates": [
    "{{ if or (.Repo.Working.Changed) (.Repo.Staging.Changed) }}#f36943{{ end }}",
    "{{ if and (gt .Repo.Ahead 0) (gt .Repo.Behind 0) }}#a8216b{{ end }}",
    "{{ if gt .Repo.Ahead 0 }}#35b5ff{{ end }}",
    "{{ if gt .Repo.Behind 0 }}#f89cfa{{ end }}"
  ],
  "powerline_symbol": "",
  "properties": {
    "display_status": true,
    "branch_max_length": 25,
    "template": "{{ .Repo.HEAD }}{{ .Repo.BranchStatus }}{{ if .Repo.Working.Changed }} \uF044 {{ .Repo.Working.String }}{{ end }}{{ if .Repo.Staging.Changed }} \uF046 {{ .Repo.Staging.String }}{{ end }}"
  }
}
```

**Comment by lnu** [comment]
> You can now also do this, which is fricking amazing:
> 
> ```json
> {
>   "type": "git",
>   "style": "powerline",
>   "foreground": "#193549",
>   "foreground_templates": [
>     "{{ if and (gt .Repo.Ahead 0) (gt .Repo.Behind 0) }}#ffffff{{ end }}"
>   ],
>   "background": "#2e9599",
>   "background_templates": [
>     "{{ if or (.Repo.Working.Changed) (.Repo.Staging.Changed) }}#f36943{{ end }}",
>     "{{ if and (gt .Repo.Ahead 0) (gt .Repo.Behind 0) }}#a8216b{{ end }}",
>     "{{ if gt .Repo.Ahead 0 }}#35b5ff{{ end }}",
>     "{{ if gt .Repo.Behind 0 }}#f89cfa{{ end }}"
>   ],
>   "powerline_symbol": "",
>   "properties": {
>     "display_status": true,
>     "branch_max_length": 25,
>     "template": "{{ .Repo.HEAD }}{{ .Repo.BranchStatus }}{{ if .Repo.Working.Changed }} \uF044 {{ .Repo.Working.String }}{{ end }}{{ if .Repo.Staging.Changed }} \uF046 {{ .Repo.Staging.String }}{{ end }}"
>   }
> }
> ```

That’s what I was looking for this morning. So we can change the color like it was done with the status_color_enabled?

**Comment by JanDeDobbeleer** [comment]
> That’s what I was looking for this morning. So we can change the color like it was done with the status_color_enabled?

Yes, but even better. Previously you could only change the back- or foreground. Now you can do anything you want.

**Comment by lnu** [comment]
Not really related to the change but the commit/tag/merge icon displays is a bit truncated by default:
image

I only add a space after the font in my config and it's better:
image

**Comment by JanDeDobbeleer** [comment]
I'll create a quick fix for that.

**Comment by lnu** [comment]
it was there before your change so it's not so urgent. In the end I have the same command line as before with the new template using colors in the template to simulate color_status. Good job :wink:.

**Pull request merged**
