### PR TITLE
feat(themes): added new theme - slimfat - a fork of DamianoPellegrini's slim

### PR DESCRIPTION
**Pull request by irdkwmnsb**
I'd like to contribute to the themes variety of oh my posh.

I really liked @DamianoPellegrini's slim theme (#346) , but the path seemed too short. So this is a fork of their theme with the full path displayed.

Example: 
image

### CODE REVIEW

**Comment by irdkwmnsb** [comment]
After ~a little~ much googling and github issues browsing I found out that oh my posh can omit osc 9;9 codes. 

I don't know why it should be enabled manualy in themes, seems like it should be on by default.

**Comment by JanDeDobbeleer** [comment]
@irdkwmnsb not all terminals support it. So it's waste at times 😉

**Comment by irdkwmnsb** [comment]
Should I remove it then? Or leave it as is?

**Comment by JanDeDobbeleer** [comment]
@irdkwmnsb it has the downside of having a bell sound in iTerm for example (it's not a standard, but first and foremost a notification). So removing it would indeed be the best solution for standard themes. Also, can you stick to one commit for this context?

**Pull request merged**
