### PR TITLE
feat(segment): add aurelia

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

relates to #5835 

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by ernstc** [comment]
Hi @JanDeDobbeleer , if possible I would like to be added in the list of contributors for this PR. Thanks. In the commits I see a contributor but he is not me.

I have checked files
* .all-contributorsrc
* website/docs/contributors.md

**Comment by JanDeDobbeleer** [comment]
@ernstc don't worry, will be done 👍🏻

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @ernstc for code,doc

This is pure magic 🪄! @holopin-bot @ernstc wizard

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @ernstc for code,doc

**Pull request merged**
