### PR TITLE
Revert broken commits

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

@lewis-yeung as I have no idea which commit really introduces the issue (or due to both), I’m reverting both of them as I can’t test.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by lewis-yeung** [comment]
Wait, you only have to revert #5456. :)

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung we can always reintroduced. I can't test so decided to go back entirely.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I have tested and definitely confirm it's #5456 (see [my comment][comment] posted a few hours ago). Anyway, I'm trying my best to find a fix.

[comment]: https://github.com/JanDeDobbeleer/oh-my-posh/issues/5468#issuecomment-2295500633

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I trust you, it's just that my internet is so limited here I was happy I was able to revert at all 😅

**Pull request merged**
