### PR TITLE
fix(git): detect when upstream no longer exists

### PR DESCRIPTION
**Pull request by cdonnellytx**
### Prerequisites

- [X] I have read and understood the `CONTRIBUTING` guide
- [X] The commit message follows the [conventional commits][cc] guidelines
- [X] Tests for the changes have been added (for bug fixes/features)
- [X] Docs have been added / updated (for bug fixes/features)

### Description

Currently the git segment does not detect when an upstream is removed (e.g., a PR is merged and the remote branch is deleted).

This change adds functionality to detect when upstream is removed; if the porcelain status reports `branch.upstream` but no `branch.ab`, it is considered _gone_.

The UI has also been changed to reflect this third state; it now matches posh-git's behavior, which only shows the Gone icon if an upstream branch is set but does not report ahead/behind counts.

### Example

This is what the `jandedobbeleer` theme should show in each case:

| State | Before | After | Notes |
|:------|:------|:------|:------|
| No remote | ` xyzzy ≢` | ` xyzzy` | Changed (no longer shows icon) |
| Remote, no `branch.upstream` | `xyzzy ≢` | `xyzzy` | Changed (no longer shows icon) |
| Remote, upstream exists | ` xyzzy ≡` |  ` xyzzy ≡` | Unchanged |
| Remote, upstream gone | `xyzzy ≢` | `xyzzy ≢` | Unchanged |

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
Awesome. I'll add this ASAP but you'll have to rework as #1629 is going to layout everything quite differently.

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx you can rebase this (but probably rework) on main, then we can get this baby merged!

**Comment by cdonnellytx** [comment]
OK, it's rebased to latest main.

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx I believe we can add this boolean property to the docs as well? Can be useful for coloring I suppose.

**Pull request merged**
