### PR TITLE
fix(git): read real worktree folder from gitdir

### PR DESCRIPTION
**Pull request by lnu**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [ ] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes/features)

### Description

[Description of the change]

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
Ah good, was on my list for this evening :-)

**Comment by lnu** [comment]
Still have to check how it fits with the submodule thing

**Comment by lnu** [comment]
submodules working:
image

**Comment by lnu** [comment]
I have no issues with windows path in wsl(/mnt/d/xxx) but I'll check the issue. https://github.com/JanDeDobbeleer/oh-my-posh/discussions/1195#discussioncomment-1624759

**Review by JanDeDobbeleer — APPROVED** [review]

**Pull request merged**
