### PR TITLE
Remove old fix, unhide last character from the line

### PR DESCRIPTION
**Pull request by nunu**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines

### Description

At the right segment you should add "horizontal_offset": 1,  

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by nunu** [comment]
image

**Comment by JanDeDobbeleer** [comment]
@nunu what's your motivation for this change? As changing the line start isn't the same as clearing after the cursor. And additionally it puts an action in the hands of the end user.

**Comment by nunu** [comment]
> @nunu what's your motivation for this change? As changing the line start isn't the same as clearing after the cursor. And additionally it puts an action in the hands of the end user.

for me it looks better it works just as well. 
Maybe I don't understand what it affects, do you have a link or some more information about?

**Comment by JanDeDobbeleer** [comment]
@nunu what do you mean with `it looks better`? As this has no influence on the way it looks but rather prevents it from looking bad.

**Comment by nunu** [comment]
By default one character is added to the end of line

image

I try with "horizontal_offset": 1, at right segment

And it hide last character and add empty character

image
image

If i remove those line and add "horizontal_offset": 1, it fix this

image


image

**Comment by JanDeDobbeleer** [comment]
@nunu that's weird as I don't have that? can I get your config?

**Comment by nunu** [comment]
> @nunu that's weird as I don't have that? can I get your config?

https://gist.github.com/nunu/7bac3696ae3e4b26c68f5d02aa2224c6

maybe is my wrong theme

image

**Comment by JanDeDobbeleer** [comment]
@nunu I'll check!

**Comment by JanDeDobbeleer** [comment]
@nunu I can't reproduce that block with your config. It's not there. What are your Windows Terminal settings?

**Comment by nunu** [comment]
> @nunu I can't reproduce that block with your config. It's not there. What are your Windows Terminal settings?

https://gist.github.com/nunu/3149dc2d1774baa341fb91db7f2f47f3


"initialCols": 180,
"initialRows": 36,

**Comment by georgetzlp** [comment]
This also happens to me, even happens in normal Command Prompt.

**Comment by JanDeDobbeleer** [comment]
@wathhr do you have a screenshot for "normal command prompt"? Somehow this feels like a Windows Terminal bug, not an oh-my-posh one. Just like this fix is also there to solve a PowerShell bug with colorization when at the end of the terminal screen. So removing this isn't an option.

**Comment by georgetzlp** [comment]
image
with
```json
    {
      "alignment": "right",
      "type": "prompt",
      "segments": [
        {
          "foreground": "darkGray",
          "style": "plain",
          "type": "text",
          "template": "test",
          "interactive": true
        }
      ]
    }
```

**Comment by JanDeDobbeleer** [comment]
@wathhr @nunu if this also happens on CMD, the issue is different and the proposed fix isn't the solution as that only addresses PWSH.

**Pull request closed without merging**
