### PR TITLE
Fix typos in TestCanUpgrade

### PR DESCRIPTION
**Pull request by kapsiR**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] ~~Tests for the changes have been added (for bug fixes/features)~~ **not applicable**
- [ ] ~~Docs have been added/updated (for bug fixes/features)~~ **not applicable**

### Description
This just fixes some typos of the [recent commit](393f30a082e96f7341b1e4213e80867bedeacab2) regarding the upgrade notices.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by kapsiR** [comment]
@JanDeDobbeleer Sry for the commit linting error, but is it intended that `style` is not allowed here? (since it's mentioned in the conventional commits)

Edit: Otherwise should we add the allowed ones in the contributing guidelines?

**Comment by JanDeDobbeleer** [comment]
@kapsiR the allowed ones are specified [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/393f30a082e96f7341b1e4213e80867bedeacab2/.commitlintrc.yml#L5) 😉

**Comment by kapsiR** [comment]
I saw the allowed ones in the linting error message, but I was a bit confused why not all of the conventional comments guidelines were in there...  

I understand that's defined by the project, but I would submit a PR to update the contribution guidelines to link to the allowed ones 😉

Nevertheless, I'll fix that as soon as I get to it.

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @kapsiR for code

**Pull request merged**
