### PR TITLE
feat(theme): new theme => neko

### PR DESCRIPTION
**Pull request by williamalvarezdev**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description
It's a simple theme with a cat and a smiley face, the cat asks what it needs to do next and the face is the one responding.

The text after the home emoji is the HEAD of the git, and the time is the current time.

I have borrowed most of the theme from "material", but I just added this as there is a lack of "cute" minimalistic themes. 
Neko theme

I hope I have followed all the guidelines. I have run the tests `go test -v ./...` as suggested on the contribution page in the docs. They all passed.

Please let me know if I have missed something or if there is no need for this type of theme 😃 

 

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by ehawman-rosenberg** [comment]
@williamalvarez92 This is ADORABLE.

**Comment by williamalvarezdev** [comment]
> @williamalvarez92 This is ADORABLE.

Thanks!! Glad you liked it :D

**Comment by JanDeDobbeleer** [comment]
It's a really refreshing one indeed. I was wondering if the initial spacing on the second line (it's a bit indented) is intentional?

**Comment by williamalvarezdev** [comment]
I wrote the `newline: True` previously, but it looked too compacted. Then I made it that way, wrote it in a separate block, and it gave it that space (I don't know why). I personally like that it makes it look more like a conversation. But I guess it depends on the person.

That said, that is how it worked on my terminal, I don't know if it would behave the same way on other people's terminals.

**Comment by ehawman-rosenberg** [comment]
I, too, think it looks a bit more conversational with a slight offset.

**Comment by williamalvarezdev** [comment]
Sorry I tried to merge it twice now. Let me kmow if I should do something about it

**Pull request merged**
