### PR TITLE
gap between arrow and directory

### PR DESCRIPTION
**Pull request by BabcB**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by ehawman-rosenberg** [comment]
@BabcB you'll need to change your commit message to be something like `fix(theme): tweaked spacing in atomic theme path seg` (GitKraken makes this super easy, btw)

If you aren't the author of the atomic theme, I'd recommend making a copy for yourself and hosting your own edits. If you make truly substantial edits, you can submit it as its own theme here.

If you want your custom theme to be available in multiple places, do this:

1. Save your custom theme to gist.github.com
2. Click on the "Raw" button.
3. Delete the individual commit out of the URL, then copy what remains.
`https://gist.githubusercontent.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/ff95063d74b65937eb45b1afa70d48a82ae4565d/devious-diamonds.omp.json` becomes
`https://gist.githubusercontent.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/devious-diamonds.omp.json`
4. Wherever you're summoning OMP, submit this string in for `--config`
This is in my PowerShell PS1 file:
``` pwsh
$themeJsonUrl = "https://gist.github.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/devious-diamonds.omp.json"
oh-my-posh --init --shell pwsh --config $themeJsonUrl | Invoke-Expression
```
And this is in `~/.config/fish/config.fish`
``` sh
oh-my-posh init fish --config 'https://gist.github.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/devious-diamonds.omp.json' | source
```

**Comment by lewis-yeung** [comment]
Just in addition:

1. Different users use different Nerd Fonts (sometimes customized/non-standard ones) which can have different glyph widths for the same codepoint. In a way, themes shipped with OMP act as basic templates. The space-padding for beautifying the prompt display should be up to users.

2. Besides, the final rendering effect is related to specific terminal apps.

**Comment by BabcB** [comment]
Thanks for the replay. I am using the atomic theme and Windows Terminal.
Please tell me if you know what Nerd Font is compatible for this theme.

Thank you

**Comment by ehawman-rosenberg** [comment]
@BabcB any Nerd Font should work just fine. @lewis-yeung is saying that different Nerd Fonts can have slightly different spacing, so making a universal change to a theme file could have wildly different results for different users (depending on which font they chose).

If *you* think that there needs to be more space in a particular theme, make a copy and edit it as you see fit! If you need more assistance than what I've already laid out, let me know what part is giving you trouble and I can clarify.

**Comment by BabcB** [comment]
Thank you for the replay. I understand what you mean.
I use 'Hack Nerd Font'. and I get no space for 'atomic theme'.
I just want to know if anyone know a Nerd Font that gives space. Because when I update the Oh-My-Posh the changes I made are replaced.

Thank you for your time

**Comment by ehawman-rosenberg** [comment]
@BabcB Ah I see the root of the problem now.

If your tweaks are getting overwritten, you *need* to create a copy and make edits to the copy. You can create `atomic-BabcB.omp.json` in the same folder which will never get overwritten. You can also create atomic-BabcB.omp.json in a [gist](https://gist.github.com/) (referencing it as I laid out above) and it will never get overwritten. I highly recommend the latter method, since you can easily use your custom theme from any computer with internet access.

Hack is a good font. I am a diehard monospace font fan and highly recommend the Caskadia Cove Nerd Font 🤟🏻

**Comment by BabcB** [comment]
Thank you for the replay it was very useful.
I have created a seperate file and copied the code with the edit.
Thank you for the support @ehawman-rosenberg.

**Pull request closed without merging**
