### PR TITLE
fix(project): fully qualified project path

### PR DESCRIPTION
**Pull request by lnu**
fix an issue with pwsh reading the file from users home instead of cwd

### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes/features)

### Description

https://github.com/JanDeDobbeleer/oh-my-posh/issues/2033

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Review by JanDeDobbeleer — APPROVED** [review]
Just a test to be fixed by adding the mock and we're good to go. Thanks, I didn't understand why this was happening tbh.

**Comment by JanDeDobbeleer** [comment]
@lnu ~~should we add that logic (prepending the path) to the `FileContent` function instead? As I don't think we ever use it to fetch content other than the current folder.~~

We actually do, so it becomes the responsibility of the caller. Unless this could work:

```diff
diff --git a/src/environment/shell.go b/src/environment/shell.go
index 6e895421..a6b1ffe7 100644
--- a/src/environment/shell.go
+++ b/src/environment/shell.go
@@ -397,6 +397,9 @@ func (env *ShellEnvironment) HasFolder(folder string) bool {
 
 func (env *ShellEnvironment) FileContent(file string) string {
 	defer env.trace(time.Now(), "FileContent", file)
+	if !filepath.IsAbs(file) {
+		file = filepath.Join(env.Pwd(), file)
+	}
 	content, err := ioutil.ReadFile(file)
 	if err != nil {
 		env.log(Error, "FileContent", err.Error())
```

UPDATE: the above works like a charm

**Review by JanDeDobbeleer — CHANGES_REQUESTED** [review]
Let's try with the proposal I added, can validate later today.

**Comment by lnu** [comment]
Did the proposed change. Works on my side too.

**Comment by lnu** [comment]
It comes from the utf8 process startup refactoring. Since the refactoring, the startup folder is set to the home of the user and not the current path. Tried with an older version of the code and now it works.

**Comment by lnu** [comment]
should be fixed with the second commit

**Comment by lnu** [comment]
We had other issues in the past with some segments relying on the PWD parameter and others relying on the current working directory. There are probably other cases like this one hidden somewhere.

**Comment by JanDeDobbeleer** [comment]
@lnu indeed. This has been a recurring topic. And PowerShell is even more difficult due to PSWD and potential issues with drives.

**Review by JanDeDobbeleer — APPROVED** [review]

**Pull request merged**
